# AUTOGENERATED by `cargo run -p pcv-graph --bin dump_schema`. DO NOT EDIT.
# Source of truth: `pcv-graph` op registry.
from polars_cv._types import AlphaMode, DTypeEffect, NdimEffect, OpContract

WIRE_VERSION: int = 2

OPERATION_CONTRACTS: dict[str, OpContract] = {
    "adjust_contrast": OpContract(DTypeEffect.PROMOTE_TO_FLOAT, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "adjust_gamma": OpContract(DTypeEffect.PROMOTE_TO_FLOAT, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "blur": OpContract(DTypeEffect.FIXED_U8, NdimEffect.PRESERVE, AlphaMode.STRIP_PROCESS_RESTORE),
    "canny": OpContract(DTypeEffect.FIXED_U8, NdimEffect.PRESERVE, AlphaMode.DROP),
    "cast": OpContract(DTypeEffect.FIXED_U8, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "channel_select": OpContract(DTypeEffect.PRESERVE, NdimEffect.REDUCE_ONE, AlphaMode.DROP),
    "clamp": OpContract(DTypeEffect.PROMOTE_TO_FLOAT, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "crop": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "dilate": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.DROP),
    "equalize_histogram": OpContract(DTypeEffect.FIXED_U8, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "erode": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.DROP),
    "flip": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "grayscale": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.DROP),
    "identity": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "invert": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "morphology_gradient": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.DROP),
    "normalize": OpContract(DTypeEffect.CONFIGURABLE_F32, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "relu": OpContract(DTypeEffect.PROMOTE_TO_FLOAT, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "reshape": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "rotate": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "scale": OpContract(DTypeEffect.PROMOTE_TO_FLOAT, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
    "threshold": OpContract(DTypeEffect.FIXED_U8, NdimEffect.PRESERVE, AlphaMode.DROP),
    "transpose": OpContract(DTypeEffect.PRESERVE, NdimEffect.PRESERVE, AlphaMode.PASSTHROUGH),
}
