"""Dtype spellings, generated from ``dtype_table!``. Do not edit by hand.

``view-buffer/src/core/dtype.rs`` is the single authority for how a dtype is
spelled. This module is that table's Python face, regenerated by::

    python scripts/gen_dtype_names.py

``tests/test_sanitation.py::test_dtype_names_module_is_current`` fails if it is
stale, so the copy cannot drift from the table it came from.

Only the spellings live here. Which of them a given surface *accepts* is that
surface's own question — the numpy sink emits ``NUMPY_NAMES`` and nothing else,
so that is what ``numpy_from_struct`` admits.
"""

from __future__ import annotations

#: Engine dtype names, as ``.cast()`` and ``source(dtype=)`` take them.
SHORT_NAMES: frozenset[str] = frozenset(
    ["f32", "f64", "i16", "i32", "i64", "i8", "u16", "u32", "u64", "u8"]
)

#: numpy dtype names, as the numpy/torch sink writes them into its struct.
#:
#: Deliberately not numpy's character codes. An earlier hand-written copy
#: admitted those, which put ``"u8"`` (numpy ``uint64``) in the same set as
#: this project's ``"u8"`` (``uint8``) — opposite meanings for one string.
NUMPY_NAMES: frozenset[str] = frozenset(
    [
        "float32",
        "float64",
        "int16",
        "int32",
        "int64",
        "int8",
        "uint16",
        "uint32",
        "uint64",
        "uint8",
    ]
)

#: Every name the numpy/torch sink can write, which is one more than the
#: engine has dtypes for: ``.sink("numpy", dtype="f16")`` downcasts float
#: to half *at the encode boundary*, so ``float16`` reaches a consumer
#: without ever being a `dtype_table!` row. Spelled as an explicit union
#: rather than folded into the table: it is a property of the sink, not of
#: the engine's dtype vocabulary.
SINK_NUMPY_NAMES: frozenset[str] = NUMPY_NAMES | {"float16"}

#: Short name -> VIEW binary protocol code.
WIRE_CODES: dict[str, int] = {
    "u8": 1,
    "i8": 2,
    "u16": 3,
    "i16": 4,
    "u32": 5,
    "i32": 6,
    "u64": 9,
    "i64": 10,
    "f32": 7,
    "f64": 8,
}

#: VIEW binary protocol code -> numpy name. The reverse of
#: :data:`WIRE_CODES` composed with the numpy spelling, emitted as one
#: table because reading a VIEW blob needs exactly that hop and nothing
#: else. `display.py` used to hand-write it, which made a third Python
#: copy of `dtype_table!` guarded only by a regex over its own source.
NUMPY_BY_WIRE_CODE: dict[int, str] = {
    1: "uint8",
    2: "int8",
    3: "uint16",
    4: "int16",
    5: "uint32",
    6: "int32",
    7: "float32",
    8: "float64",
    9: "uint64",
    10: "int64",
}
