# This file is generated by scripts/gen_ops.py from the built Pipeline class.
# Do not edit by hand: change Pipeline (or the Rust catalogue it is generated
# from), then rerun the generator.
"""``LazyPipelineExpr``'s chainable operations, one per ``Pipeline`` method."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

    import polars as pl

    from polars_cv._types import BoolOrExpr, FloatOrExpr, IntOrExpr
    from polars_cv.lazy import LazyPipelineExpr
    from polars_cv.pipeline import Pipeline


class _LazyForwardersMixin:
    """The generated chainable operations ``LazyPipelineExpr`` inherits."""

    if TYPE_CHECKING:

        def pipe(self, pipeline: Pipeline) -> LazyPipelineExpr: ...
        def _continuation(self) -> Pipeline: ...

    def abs(self) -> LazyPipelineExpr:
        """Absolute value (`|x|`). Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.abs` on this expression's output.
        """
        return self.pipe(self._continuation().abs())

    def add_constant(self, value: FloatOrExpr) -> LazyPipelineExpr:
        """Add a constant to every value (`x + value`).

        Lazy form of :meth:`Pipeline.add_constant` on this expression's output.
        """
        return self.pipe(self._continuation().add_constant(value=value))

    def adjust_brightness(
        self, *, factor: FloatOrExpr, preserve_dtype: bool = False
    ) -> LazyPipelineExpr:
        """Adjust image brightness by scaling pixel values.

        Lazy form of :meth:`Pipeline.adjust_brightness` on this expression's output.
        """
        return self.pipe(
            self._continuation().adjust_brightness(
                factor=factor, preserve_dtype=preserve_dtype
            )
        )

    def adjust_contrast(self, factor: FloatOrExpr) -> LazyPipelineExpr:
        """Adjust image contrast: `(pixel - mean) * factor + mean`.

        Lazy form of :meth:`Pipeline.adjust_contrast` on this expression's output.
        """
        return self.pipe(self._continuation().adjust_contrast(factor=factor))

    def adjust_gamma(self, gamma: FloatOrExpr) -> LazyPipelineExpr:
        """Apply gamma (power-law) correction: normalize to [0,1], raise to `gamma`,

        Lazy form of :meth:`Pipeline.adjust_gamma` on this expression's output.
        """
        return self.pipe(self._continuation().adjust_gamma(gamma=gamma))

    def area(self, *, signed: BoolOrExpr = False) -> LazyPipelineExpr:
        """Compute the area of the contour using the Shoelace formula.

        Lazy form of :meth:`Pipeline.area` on this expression's output.
        """
        return self.pipe(self._continuation().area(signed=signed))

    def assert_shape(
        self,
        *,
        dims: Sequence[int | None] | None = None,
        height: IntOrExpr | None = None,
        width: IntOrExpr | None = None,
        channels: IntOrExpr | None = None,
    ) -> LazyPipelineExpr:
        """Declare a shape the planner cannot work out for itself.

        Lazy form of :meth:`Pipeline.assert_shape` on this expression's output.
        """
        return self.pipe(
            self._continuation().assert_shape(
                dims=dims, height=height, width=width, channels=channels
            )
        )

    def blur(self, sigma: FloatOrExpr) -> LazyPipelineExpr:
        """Apply Gaussian blur.

        Lazy form of :meth:`Pipeline.blur` on this expression's output.
        """
        return self.pipe(self._continuation().blur(sigma=sigma))

    def bounding_box(self) -> LazyPipelineExpr:
        """Compute the axis-aligned bounding box of the contour.

        Lazy form of :meth:`Pipeline.bounding_box` on this expression's output.
        """
        return self.pipe(self._continuation().bounding_box())

    def canny(
        self, *, low_threshold: FloatOrExpr = 50.0, high_threshold: FloatOrExpr = 150.0
    ) -> LazyPipelineExpr:
        """Canny edge detection: Gaussian blur, Sobel gradients, non-maximum

        Lazy form of :meth:`Pipeline.canny` on this expression's output.
        """
        return self.pipe(
            self._continuation().canny(
                low_threshold=low_threshold, high_threshold=high_threshold
            )
        )

    def cast(self, dtype: str) -> LazyPipelineExpr:
        """Cast to a different data type.

        Lazy form of :meth:`Pipeline.cast` on this expression's output.
        """
        return self.pipe(self._continuation().cast(dtype=dtype))

    def ceil(self) -> LazyPipelineExpr:
        """Round toward positive infinity. Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.ceil` on this expression's output.
        """
        return self.pipe(self._continuation().ceil())

    def centroid(self) -> LazyPipelineExpr:
        """Compute the centroid (center of mass) of the contour.

        Lazy form of :meth:`Pipeline.centroid` on this expression's output.
        """
        return self.pipe(self._continuation().centroid())

    def channel_select(self, index: IntOrExpr) -> LazyPipelineExpr:
        """Extract a single channel from a multi-channel image: a 2D [H, W] buffer

        Lazy form of :meth:`Pipeline.channel_select` on this expression's output.
        """
        return self.pipe(self._continuation().channel_select(index=index))

    def channel_swap(self, order: Sequence[IntOrExpr]) -> LazyPipelineExpr:
        """Reorder channels in a multi-channel image.

        Lazy form of :meth:`Pipeline.channel_swap` on this expression's output.
        """
        return self.pipe(self._continuation().channel_swap(order=order))

    def clamp(
        self,
        min_val: FloatOrExpr,
        max_val: FloatOrExpr,
        out_dtype: str | None = None,
        preserve_dtype: bool = False,
    ) -> LazyPipelineExpr:
        """Clamp values to a range.

        Lazy form of :meth:`Pipeline.clamp` on this expression's output.
        """
        return self.pipe(
            self._continuation().clamp(
                min_val=min_val,
                max_val=max_val,
                out_dtype=out_dtype,
                preserve_dtype=preserve_dtype,
            )
        )

    def clamp_max(self, value: FloatOrExpr) -> LazyPipelineExpr:
        """Cap values at `value` (`min(x, value)`); one-sided clamp.

        Lazy form of :meth:`Pipeline.clamp_max` on this expression's output.
        """
        return self.pipe(self._continuation().clamp_max(value=value))

    def clamp_min(self, value: FloatOrExpr) -> LazyPipelineExpr:
        """Floor values at `value` (`max(x, value)`); one-sided clamp.

        Lazy form of :meth:`Pipeline.clamp_min` on this expression's output.
        """
        return self.pipe(self._continuation().clamp_min(value=value))

    def convert_color(self, *, from_space: str, to_space: str) -> LazyPipelineExpr:
        """Convert between color spaces.

        Lazy form of :meth:`Pipeline.convert_color` on this expression's output.
        """
        return self.pipe(
            self._continuation().convert_color(from_space=from_space, to_space=to_space)
        )

    def convex_hull(self) -> LazyPipelineExpr:
        """Compute the convex hull of the contour.

        Lazy form of :meth:`Pipeline.convex_hull` on this expression's output.
        """
        return self.pipe(self._continuation().convex_hull())

    def convolve2d(
        self,
        kernel: Sequence[FloatOrExpr],
        *,
        normalize: BoolOrExpr = False,
        border: str | pl.Expr = "replicate",
    ) -> LazyPipelineExpr:
        """Apply generic 2D convolution with an arbitrary kernel.

        Lazy form of :meth:`Pipeline.convolve2d` on this expression's output.
        """
        return self.pipe(
            self._continuation().convolve2d(
                kernel=kernel, normalize=normalize, border=border
            )
        )

    def crop(
        self,
        *,
        top: IntOrExpr = 0,
        left: IntOrExpr = 0,
        height: IntOrExpr | None = None,
        width: IntOrExpr | None = None,
    ) -> LazyPipelineExpr:
        """Extract a rectangular region.

        Lazy form of :meth:`Pipeline.crop` on this expression's output.
        """
        return self.pipe(
            self._continuation().crop(top=top, left=left, height=height, width=width)
        )

    def dilate(
        self, *, ksize: IntOrExpr = 3, iterations: IntOrExpr = 1
    ) -> LazyPipelineExpr:
        """Morphological dilation (local maximum over a `ksize × ksize` square). Requires single-channel input (e.g. after `.grayscale()` or `.threshold()`).

        Lazy form of :meth:`Pipeline.dilate` on this expression's output.
        """
        return self.pipe(
            self._continuation().dilate(ksize=ksize, iterations=iterations)
        )

    def equalize_histogram(self) -> LazyPipelineExpr:
        """Apply histogram equalization for contrast enhancement: map each pixel

        Lazy form of :meth:`Pipeline.equalize_histogram` on this expression's output.
        """
        return self.pipe(self._continuation().equalize_histogram())

    def erode(
        self, *, ksize: IntOrExpr = 3, iterations: IntOrExpr = 1
    ) -> LazyPipelineExpr:
        """Morphological erosion (local minimum over a `ksize × ksize` square). Requires single-channel input (e.g. after `.grayscale()` or `.threshold()`).

        Lazy form of :meth:`Pipeline.erode` on this expression's output.
        """
        return self.pipe(self._continuation().erode(ksize=ksize, iterations=iterations))

    def extract_contours(
        self,
        *,
        mode: str | pl.Expr = "external",
        method: str | pl.Expr = "simple",
        min_area: FloatOrExpr | None = None,
    ) -> LazyPipelineExpr:
        """Extract contours from binary mask.

        Lazy form of :meth:`Pipeline.extract_contours` on this expression's output.
        """
        return self.pipe(
            self._continuation().extract_contours(
                mode=mode, method=method, min_area=min_area
            )
        )

    def extract_shape(self) -> LazyPipelineExpr:
        """Extract buffer shape as a struct {height, width, channels}.

        Lazy form of :meth:`Pipeline.extract_shape` on this expression's output.
        """
        return self.pipe(self._continuation().extract_shape())

    def flip(self, axes: Sequence[int]) -> LazyPipelineExpr:
        """Flip along specified axes.

        Lazy form of :meth:`Pipeline.flip` on this expression's output.
        """
        return self.pipe(self._continuation().flip(axes=axes))

    def flip_h(self) -> LazyPipelineExpr:
        """Flip horizontally (along width axis).

        Lazy form of :meth:`Pipeline.flip_h` on this expression's output.
        """
        return self.pipe(self._continuation().flip_h())

    def flip_v(self) -> LazyPipelineExpr:
        """Flip vertically (along height axis).

        Lazy form of :meth:`Pipeline.flip_v` on this expression's output.
        """
        return self.pipe(self._continuation().flip_v())

    def floor(self) -> LazyPipelineExpr:
        """Round toward negative infinity. Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.floor` on this expression's output.
        """
        return self.pipe(self._continuation().floor())

    def grayscale(self) -> LazyPipelineExpr:
        """Convert to grayscale (luminance 0.299R + 0.587G + 0.114B).

        Lazy form of :meth:`Pipeline.grayscale` on this expression's output.
        """
        return self.pipe(self._continuation().grayscale())

    def histogram(
        self,
        *,
        bins: IntOrExpr | Sequence[float] = 256,
        range: Sequence[FloatOrExpr] | None = None,
        closed: str = "left",
        output: str = "buckets",
    ) -> LazyPipelineExpr:
        """Compute pixel value histogram.

        Lazy form of :meth:`Pipeline.histogram` on this expression's output.
        """
        return self.pipe(
            self._continuation().histogram(
                bins=bins, range=range, closed=closed, output=output
            )
        )

    def invert(self) -> LazyPipelineExpr:
        """Invert pixel values: `255 - pixel` for u8, `1.0 - pixel` for float [0,1].

        Lazy form of :meth:`Pipeline.invert` on this expression's output.
        """
        return self.pipe(self._continuation().invert())

    def label_reduce(
        self,
        contours: pl.Expr,
        *,
        reduction: str | pl.Expr = "max",
        region_mode: str | pl.Expr = "interior",
    ) -> LazyPipelineExpr:
        """Score contour regions against the current buffer values.

        Lazy form of :meth:`Pipeline.label_reduce` on this expression's output.
        """
        return self.pipe(
            self._continuation().label_reduce(
                contours=contours, reduction=reduction, region_mode=region_mode
            )
        )

    def laplacian(self, *, ksize: int = 3) -> LazyPipelineExpr:
        """Laplacian second-derivative operator.

        Lazy form of :meth:`Pipeline.laplacian` on this expression's output.
        """
        return self.pipe(self._continuation().laplacian(ksize=ksize))

    def letterbox(
        self,
        *,
        height: IntOrExpr,
        width: IntOrExpr,
        value: FloatOrExpr = 0.0,
        filter: str | pl.Expr = "lanczos3",
    ) -> LazyPipelineExpr:
        """Resize image maintaining aspect ratio and pad to exact target size: fit

        Lazy form of :meth:`Pipeline.letterbox` on this expression's output.
        """
        return self.pipe(
            self._continuation().letterbox(
                height=height, width=width, value=value, filter=filter
            )
        )

    def morphology_close(self, *, ksize: IntOrExpr = 3) -> LazyPipelineExpr:
        """Morphological closing (dilate then erode).

        Lazy form of :meth:`Pipeline.morphology_close` on this expression's output.
        """
        return self.pipe(self._continuation().morphology_close(ksize=ksize))

    def morphology_gradient(self, *, ksize: IntOrExpr = 3) -> LazyPipelineExpr:
        """Morphological gradient (dilate - erode): an edge outline. Requires

        Lazy form of :meth:`Pipeline.morphology_gradient` on this expression's output.
        """
        return self.pipe(self._continuation().morphology_gradient(ksize=ksize))

    def morphology_open(self, *, ksize: IntOrExpr = 3) -> LazyPipelineExpr:
        """Morphological opening (erode then dilate).

        Lazy form of :meth:`Pipeline.morphology_open` on this expression's output.
        """
        return self.pipe(self._continuation().morphology_open(ksize=ksize))

    def neg(self) -> LazyPipelineExpr:
        """Negate every value (`-x`). Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.neg` on this expression's output.
        """
        return self.pipe(self._continuation().neg())

    def normalize(
        self,
        *,
        method: str = "minmax",
        mean: Sequence[FloatOrExpr] | None = None,
        std: Sequence[FloatOrExpr] | None = None,
        out_dtype: str | None = None,
    ) -> LazyPipelineExpr:
        """Normalize values to a standard range.

        Lazy form of :meth:`Pipeline.normalize` on this expression's output.
        """
        return self.pipe(
            self._continuation().normalize(
                method=method, mean=mean, std=std, out_dtype=out_dtype
            )
        )

    def on_error(self, policy: str) -> LazyPipelineExpr:
        """Set the per-row error policy for the executed pipeline graph.

        Lazy form of :meth:`Pipeline.on_error` on this expression's output.
        """
        return self.pipe(self._continuation().on_error(policy=policy))

    def on_null_param(self, policy: str) -> LazyPipelineExpr:
        """Set what a null in a per-row expression parameter means.

        Lazy form of :meth:`Pipeline.on_null_param` on this expression's output.
        """
        return self.pipe(self._continuation().on_null_param(policy=policy))

    def pad(
        self,
        *,
        top: IntOrExpr = 0,
        bottom: IntOrExpr = 0,
        left: IntOrExpr = 0,
        right: IntOrExpr = 0,
        value: FloatOrExpr = 0.0,
        mode: str | pl.Expr = "constant",
    ) -> LazyPipelineExpr:
        """Add padding to the image.

        Lazy form of :meth:`Pipeline.pad` on this expression's output.
        """
        return self.pipe(
            self._continuation().pad(
                top=top, bottom=bottom, left=left, right=right, value=value, mode=mode
            )
        )

    def pad_to_size(
        self,
        *,
        height: IntOrExpr,
        width: IntOrExpr,
        position: str | pl.Expr = "center",
        value: FloatOrExpr = 0.0,
    ) -> LazyPipelineExpr:
        """Pad image to exact target size (computed at runtime). A larger image is

        Lazy form of :meth:`Pipeline.pad_to_size` on this expression's output.
        """
        return self.pipe(
            self._continuation().pad_to_size(
                height=height, width=width, position=position, value=value
            )
        )

    def perceptual_hash(
        self, *, algorithm: str = "perceptual", hash_size: int = 64
    ) -> LazyPipelineExpr:
        """Compute a perceptual hash fingerprint.

        Lazy form of :meth:`Pipeline.perceptual_hash` on this expression's output.
        """
        return self.pipe(
            self._continuation().perceptual_hash(
                algorithm=algorithm, hash_size=hash_size
            )
        )

    def perimeter(self) -> LazyPipelineExpr:
        """Compute the perimeter (arc length) of the contour.

        Lazy form of :meth:`Pipeline.perimeter` on this expression's output.
        """
        return self.pipe(self._continuation().perimeter())

    def rasterize(
        self,
        *,
        width: IntOrExpr | None = None,
        height: IntOrExpr | None = None,
        shape: LazyPipelineExpr | None = None,
        fill_value: IntOrExpr = 255,
        background: IntOrExpr = 0,
    ) -> LazyPipelineExpr:
        """Rasterize contours to a binary mask.

        Lazy form of :meth:`Pipeline.rasterize` on this expression's output.
        """
        return self.pipe(
            self._continuation().rasterize(
                width=width,
                height=height,
                shape=shape,
                fill_value=fill_value,
                background=background,
            )
        )

    def reciprocal(self) -> LazyPipelineExpr:
        """Reciprocal (`1 / x`; ±inf at zero). Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.reciprocal` on this expression's output.
        """
        return self.pipe(self._continuation().reciprocal())

    def reduce_argmax(self, axis: int) -> LazyPipelineExpr:
        """Index of the maximum value along an axis.

        Lazy form of :meth:`Pipeline.reduce_argmax` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_argmax(axis=axis))

    def reduce_argmin(self, axis: int) -> LazyPipelineExpr:
        """Index of the minimum value along an axis.

        Lazy form of :meth:`Pipeline.reduce_argmin` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_argmin(axis=axis))

    def reduce_max(self, *, axis: int | None = None) -> LazyPipelineExpr:
        """Reduce buffer by computing the maximum value.

        Lazy form of :meth:`Pipeline.reduce_max` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_max(axis=axis))

    def reduce_mean(self, *, axis: int | None = None) -> LazyPipelineExpr:
        """Compute arithmetic mean.

        Lazy form of :meth:`Pipeline.reduce_mean` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_mean(axis=axis))

    def reduce_min(self, *, axis: int | None = None) -> LazyPipelineExpr:
        """Reduce buffer by computing the minimum value.

        Lazy form of :meth:`Pipeline.reduce_min` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_min(axis=axis))

    def reduce_percentile(self, q: FloatOrExpr) -> LazyPipelineExpr:
        """Compute the q-th percentile of all values (linear interpolation, as numpy's

        Lazy form of :meth:`Pipeline.reduce_percentile` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_percentile(q=q))

    def reduce_popcount(self) -> LazyPipelineExpr:
        """Count set bits (1s) in the buffer.

        Lazy form of :meth:`Pipeline.reduce_popcount` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_popcount())

    def reduce_std(
        self, *, axis: int | None = None, ddof: IntOrExpr = 0
    ) -> LazyPipelineExpr:
        """Reduce buffer by computing the standard deviation.

        Lazy form of :meth:`Pipeline.reduce_std` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_std(axis=axis, ddof=ddof))

    def reduce_sum(self) -> LazyPipelineExpr:
        """Sum all elements in the buffer.

        Lazy form of :meth:`Pipeline.reduce_sum` on this expression's output.
        """
        return self.pipe(self._continuation().reduce_sum())

    def relu(self) -> LazyPipelineExpr:
        """Apply ReLU activation (max(0, x)): negative values become zero.

        Lazy form of :meth:`Pipeline.relu` on this expression's output.
        """
        return self.pipe(self._continuation().relu())

    def reshape(self, shape: Sequence[IntOrExpr]) -> LazyPipelineExpr:
        """Reshape array to new dimensions.

        Lazy form of :meth:`Pipeline.reshape` on this expression's output.
        """
        return self.pipe(self._continuation().reshape(shape=shape))

    def resize(
        self, *, height: IntOrExpr, width: IntOrExpr, filter: str | pl.Expr = "lanczos3"
    ) -> LazyPipelineExpr:
        """Resize image to specified dimensions.

        Lazy form of :meth:`Pipeline.resize` on this expression's output.
        """
        return self.pipe(
            self._continuation().resize(height=height, width=width, filter=filter)
        )

    def resize_max(
        self, max_size: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> LazyPipelineExpr:
        """Resize image so the maximum dimension equals target, preserving aspect ratio (200x100 with max_size=50 gives 50x25).

        Lazy form of :meth:`Pipeline.resize_max` on this expression's output.
        """
        return self.pipe(
            self._continuation().resize_max(max_size=max_size, filter=filter)
        )

    def resize_min(
        self, min_size: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> LazyPipelineExpr:
        """Resize image so the minimum dimension equals target, preserving aspect ratio (200x100 with min_size=50 gives 100x50).

        Lazy form of :meth:`Pipeline.resize_min` on this expression's output.
        """
        return self.pipe(
            self._continuation().resize_min(min_size=min_size, filter=filter)
        )

    def resize_scale(
        self,
        *,
        scale: FloatOrExpr | None = None,
        scale_x: FloatOrExpr | None = None,
        scale_y: FloatOrExpr | None = None,
        filter: str | pl.Expr = "lanczos3",
    ) -> LazyPipelineExpr:
        """Resize image by scale factor.

        Lazy form of :meth:`Pipeline.resize_scale` on this expression's output.
        """
        return self.pipe(
            self._continuation().resize_scale(
                scale=scale, scale_x=scale_x, scale_y=scale_y, filter=filter
            )
        )

    def resize_to_height(
        self, height: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> LazyPipelineExpr:
        """Resize image to target height, preserving aspect ratio (width is computed at runtime).

        Lazy form of :meth:`Pipeline.resize_to_height` on this expression's output.
        """
        return self.pipe(
            self._continuation().resize_to_height(height=height, filter=filter)
        )

    def resize_to_width(
        self, width: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> LazyPipelineExpr:
        """Resize image to target width, preserving aspect ratio (height is computed at runtime).

        Lazy form of :meth:`Pipeline.resize_to_width` on this expression's output.
        """
        return self.pipe(
            self._continuation().resize_to_width(width=width, filter=filter)
        )

    def rotate(
        self,
        angle: FloatOrExpr,
        *,
        expand: bool = False,
        interpolation: str | pl.Expr = "bilinear",
        border_value: FloatOrExpr = 0.0,
    ) -> LazyPipelineExpr:
        """Rotate image by specified angle.

        Lazy form of :meth:`Pipeline.rotate` on this expression's output.
        """
        return self.pipe(
            self._continuation().rotate(
                angle=angle,
                expand=expand,
                interpolation=interpolation,
                border_value=border_value,
            )
        )

    def rotate_and_scale(
        self,
        *,
        angle: FloatOrExpr,
        center: tuple[FloatOrExpr, FloatOrExpr],
        output_size: tuple[IntOrExpr, IntOrExpr],
        scale: FloatOrExpr = 1.0,
    ) -> LazyPipelineExpr:
        """Combined rotation and scaling around a center point.

        Lazy form of :meth:`Pipeline.rotate_and_scale` on this expression's output.
        """
        return self.pipe(
            self._continuation().rotate_and_scale(
                angle=angle, center=center, output_size=output_size, scale=scale
            )
        )

    def round(self) -> LazyPipelineExpr:
        """Round to nearest, ties to even (matches Polars/numpy). Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.round` on this expression's output.
        """
        return self.pipe(self._continuation().round())

    def scale(
        self,
        factor: FloatOrExpr,
        out_dtype: str | None = None,
        preserve_dtype: bool = False,
    ) -> LazyPipelineExpr:
        """Multiply all values by a factor.

        Lazy form of :meth:`Pipeline.scale` on this expression's output.
        """
        return self.pipe(
            self._continuation().scale(
                factor=factor, out_dtype=out_dtype, preserve_dtype=preserve_dtype
            )
        )

    def scale_contour(
        self, *, sx: FloatOrExpr, sy: FloatOrExpr, origin: str | pl.Expr = "centroid"
    ) -> LazyPipelineExpr:
        """Scale the contour about *origin*.

        Lazy form of :meth:`Pipeline.scale_contour` on this expression's output.
        """
        return self.pipe(
            self._continuation().scale_contour(sx=sx, sy=sy, origin=origin)
        )

    def sharpen(self, *, strength: FloatOrExpr = 1.0) -> LazyPipelineExpr:
        """Sharpen using an unsharp-mask-style kernel.

        Lazy form of :meth:`Pipeline.sharpen` on this expression's output.
        """
        return self.pipe(self._continuation().sharpen(strength=strength))

    def shear(
        self,
        *,
        sx: FloatOrExpr = 0.0,
        sy: FloatOrExpr = 0.0,
        output_size: tuple[IntOrExpr, IntOrExpr],
    ) -> LazyPipelineExpr:
        """Apply a shear transformation.

        Lazy form of :meth:`Pipeline.shear` on this expression's output.
        """
        return self.pipe(
            self._continuation().shear(sx=sx, sy=sy, output_size=output_size)
        )

    def sign(self) -> LazyPipelineExpr:
        """Sign: `-1`/`0`/`+1` (`0` for ±0, NaN for NaN). Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.sign` on this expression's output.
        """
        return self.pipe(self._continuation().sign())

    def simplify(self, tolerance: FloatOrExpr) -> LazyPipelineExpr:
        """Simplify the contour using the Douglas-Peucker algorithm.

        Lazy form of :meth:`Pipeline.simplify` on this expression's output.
        """
        return self.pipe(self._continuation().simplify(tolerance=tolerance))

    def sobel(self, *, axis: str = "x", ksize: int = 3) -> LazyPipelineExpr:
        """Sobel gradient operator.

        Lazy form of :meth:`Pipeline.sobel` on this expression's output.
        """
        return self.pipe(self._continuation().sobel(axis=axis, ksize=ksize))

    def sqrt(self) -> LazyPipelineExpr:
        """Square root (`sqrt(x)`; NaN for negative input). Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.sqrt` on this expression's output.
        """
        return self.pipe(self._continuation().sqrt())

    def square(self) -> LazyPipelineExpr:
        """Square (`x * x`). Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.square` on this expression's output.
        """
        return self.pipe(self._continuation().square())

    def subtract_constant(self, value: FloatOrExpr) -> LazyPipelineExpr:
        """Subtract a constant from every value (`x - value`).

        Lazy form of :meth:`Pipeline.subtract_constant` on this expression's output.
        """
        return self.pipe(self._continuation().subtract_constant(value=value))

    def threshold(self, value: FloatOrExpr) -> LazyPipelineExpr:
        """Apply binary threshold: a U8 mask, 255 where the element exceeds `value`

        Lazy form of :meth:`Pipeline.threshold` on this expression's output.
        """
        return self.pipe(self._continuation().threshold(value=value))

    def to_bgr(self) -> LazyPipelineExpr:
        """Convert from RGB to BGR channel order.

        Lazy form of :meth:`Pipeline.to_bgr` on this expression's output.
        """
        return self.pipe(self._continuation().to_bgr())

    def to_hsv(self) -> LazyPipelineExpr:
        """Convert from RGB to HSV color space.

        Lazy form of :meth:`Pipeline.to_hsv` on this expression's output.
        """
        return self.pipe(self._continuation().to_hsv())

    def to_lab(self) -> LazyPipelineExpr:
        """Convert from RGB to CIE LAB color space.

        Lazy form of :meth:`Pipeline.to_lab` on this expression's output.
        """
        return self.pipe(self._continuation().to_lab())

    def to_ycbcr(self) -> LazyPipelineExpr:
        """Convert from RGB to YCbCr color space.

        Lazy form of :meth:`Pipeline.to_ycbcr` on this expression's output.
        """
        return self.pipe(self._continuation().to_ycbcr())

    def translate(self, *, dx: FloatOrExpr, dy: FloatOrExpr) -> LazyPipelineExpr:
        """Translate the contour by an offset.

        Lazy form of :meth:`Pipeline.translate` on this expression's output.
        """
        return self.pipe(self._continuation().translate(dx=dx, dy=dy))

    def transpose(self, axes: Sequence[int]) -> LazyPipelineExpr:
        """Transpose dimensions.

        Lazy form of :meth:`Pipeline.transpose` on this expression's output.
        """
        return self.pipe(self._continuation().transpose(axes=axes))

    def trunc(self) -> LazyPipelineExpr:
        """Round toward zero (drop the fractional part). Domain: buffer → buffer.

        Lazy form of :meth:`Pipeline.trunc` on this expression's output.
        """
        return self.pipe(self._continuation().trunc())

    def warp_affine(
        self,
        *,
        matrix: Sequence[FloatOrExpr],
        output_size: Sequence[IntOrExpr],
        interpolation: str | pl.Expr = "bilinear",
        border_value: FloatOrExpr = 0.0,
    ) -> LazyPipelineExpr:
        """Apply a 2x3 affine transformation matrix.

        Lazy form of :meth:`Pipeline.warp_affine` on this expression's output.
        """
        return self.pipe(
            self._continuation().warp_affine(
                matrix=matrix,
                output_size=output_size,
                interpolation=interpolation,
                border_value=border_value,
            )
        )
