# This file is generated by scripts/gen_ops.py from tests/golden/op_catalog.json.
# Do not edit by hand: change the op's Rust definition in src/ops/, re-bless the
# catalogue (POLARS_CV_BLESS=1 cargo test -p polars-cv catalog_matches), then
# rerun the generator.
"""Builder methods generated from the typed op catalogue."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import polars as pl

    from polars_cv._types import FloatOrExpr, IntOrExpr
    from polars_cv.pipeline import Pipeline

#: Ops whose wire form is typed (bare values and slots).
TYPED_OPS: frozenset[str] = frozenset(
    [
        "abs",
        "add_constant",
        "adjust_contrast",
        "adjust_gamma",
        "blur",
        "canny",
        "cast",
        "ceil",
        "clamp",
        "clamp_max",
        "clamp_min",
        "crop",
        "dilate",
        "equalize_histogram",
        "erode",
        "flip",
        "floor",
        "grayscale",
        "histogram",
        "invert",
        "letterbox",
        "morphology_gradient",
        "neg",
        "normalize",
        "pad",
        "pad_to_size",
        "reciprocal",
        "relu",
        "reshape",
        "resize",
        "resize_max",
        "resize_min",
        "resize_scale",
        "resize_to_height",
        "resize_to_width",
        "round",
        "scale",
        "sign",
        "sqrt",
        "square",
        "subtract_constant",
        "threshold",
        "transpose",
        "trunc",
        "warp_affine",
    ]
)

#: Each typed op's field types, as the catalogue describes them.
OP_FIELDS: dict[str, dict[str, Any]] = {
    "abs": {},
    "add_constant": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "adjust_contrast": {"factor": {"kind": "scalar", "per_row": True, "py": "float"}},
    "adjust_gamma": {"gamma": {"kind": "scalar", "per_row": True, "py": "float"}},
    "blur": {"sigma": {"kind": "scalar", "per_row": True, "py": "float"}},
    "canny": {
        "low_threshold": {"kind": "scalar", "per_row": True, "py": "float"},
        "high_threshold": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "cast": {
        "dtype": {
            "kind": "scalar",
            "per_row": False,
            "py": "DType",
            "variants": [
                "u8",
                "i8",
                "u16",
                "i16",
                "u32",
                "i32",
                "u64",
                "i64",
                "f32",
                "f64",
            ],
        }
    },
    "ceil": {},
    "clamp": {
        "min": {"kind": "scalar", "per_row": True, "py": "float"},
        "max": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "clamp_max": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "clamp_min": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "crop": {
        "top": {"kind": "scalar", "per_row": True, "py": "int"},
        "left": {"kind": "scalar", "per_row": True, "py": "int"},
        "height": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
        "width": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
    },
    "dilate": {
        "ksize": {"kind": "scalar", "per_row": True, "py": "int"},
        "iterations": {"kind": "scalar", "per_row": True, "py": "int"},
    },
    "equalize_histogram": {},
    "erode": {
        "ksize": {"kind": "scalar", "per_row": True, "py": "int"},
        "iterations": {"kind": "scalar", "per_row": True, "py": "int"},
    },
    "flip": {
        "axes": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "floor": {},
    "grayscale": {},
    "histogram": {
        "bins": {
            "kind": "one_of",
            "options": [
                {"kind": "scalar", "per_row": True, "py": "int"},
                {
                    "kind": "list",
                    "inner": {"kind": "scalar", "per_row": False, "py": "float"},
                },
            ],
        },
        "range": {
            "kind": "optional",
            "inner": {
                "kind": "array",
                "len": 2,
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "closed": {
            "kind": "scalar",
            "per_row": False,
            "py": "HistogramClosed",
            "variants": ["left", "right"],
        },
        "output": {
            "kind": "scalar",
            "per_row": False,
            "py": "HistogramOutput",
            "variants": ["counts", "normalized", "quantized", "edges", "buckets"],
        },
    },
    "invert": {},
    "letterbox": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "value": {"kind": "scalar", "per_row": True, "py": "float"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "morphology_gradient": {"ksize": {"kind": "scalar", "per_row": True, "py": "int"}},
    "neg": {},
    "normalize": {
        "method": {
            "kind": "scalar",
            "per_row": False,
            "py": "NormalizeMethod",
            "variants": ["minmax", "zscore", "preset"],
        },
        "mean": {
            "kind": "optional",
            "inner": {
                "kind": "list",
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "std": {
            "kind": "optional",
            "inner": {
                "kind": "list",
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "out_dtype": {
            "kind": "optional",
            "inner": {
                "kind": "scalar",
                "per_row": False,
                "py": "DType",
                "variants": [
                    "u8",
                    "i8",
                    "u16",
                    "i16",
                    "u32",
                    "i32",
                    "u64",
                    "i64",
                    "f32",
                    "f64",
                ],
            },
        },
    },
    "pad": {
        "top": {"kind": "scalar", "per_row": True, "py": "int"},
        "bottom": {"kind": "scalar", "per_row": True, "py": "int"},
        "left": {"kind": "scalar", "per_row": True, "py": "int"},
        "right": {"kind": "scalar", "per_row": True, "py": "int"},
        "value": {"kind": "scalar", "per_row": True, "py": "float"},
        "mode": {
            "kind": "scalar",
            "per_row": True,
            "py": "PadMode",
            "variants": ["constant", "edge", "reflect", "symmetric"],
        },
    },
    "pad_to_size": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "position": {
            "kind": "scalar",
            "per_row": True,
            "py": "PadPosition",
            "variants": ["center", "top-left", "bottom-right"],
        },
        "value": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "reciprocal": {},
    "relu": {},
    "reshape": {
        "shape": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        }
    },
    "resize": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_max": {
        "max_size": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_min": {
        "min_size": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_scale": {
        "scale_x": {"kind": "scalar", "per_row": True, "py": "float"},
        "scale_y": {"kind": "scalar", "per_row": True, "py": "float"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_to_height": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_to_width": {
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "round": {},
    "scale": {"factor": {"kind": "scalar", "per_row": True, "py": "float"}},
    "sign": {},
    "sqrt": {},
    "square": {},
    "subtract_constant": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "threshold": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "transpose": {
        "axes": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "trunc": {},
    "warp_affine": {
        "matrix": {
            "kind": "array",
            "len": 6,
            "inner": {"kind": "scalar", "per_row": True, "py": "float"},
        },
        "output_size": {
            "kind": "array",
            "len": 2,
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
        "interpolation": {
            "kind": "scalar",
            "per_row": True,
            "py": "InterpolationType",
            "variants": ["nearest", "bilinear"],
        },
        "border_value": {"kind": "scalar", "per_row": True, "py": "float"},
    },
}


class _OpsMixin:
    """The generated builder methods ``Pipeline`` inherits."""

    if TYPE_CHECKING:

        def _append_typed(self, op_name: str, values: dict[str, Any]) -> Pipeline: ...

    def abs(self) -> Pipeline:
        """Absolute value (`|x|`). Domain: buffer → buffer."""
        return self._append_typed("abs", {})

    def add_constant(self, value: FloatOrExpr) -> Pipeline:
        """Add a constant to every value (`x + value`).

        Args:
            value: Constant addend (literal or per-row expression).
        """
        return self._append_typed("add_constant", {"value": value})

    def adjust_contrast(self, *, factor: FloatOrExpr) -> Pipeline:
        """Adjust image contrast: `(pixel - mean) * factor + mean`.

        Args:
            factor: Contrast factor. 1.0 = no change, >1 = more contrast, <1 = less.

        Example:
            >>> pipe = Pipeline().source("image_bytes").adjust_contrast(factor=1.5)
        """
        return self._append_typed("adjust_contrast", {"factor": factor})

    def adjust_gamma(self, *, gamma: FloatOrExpr) -> Pipeline:
        """Apply gamma (power-law) correction: normalize to [0,1], raise to `gamma`,
        denormalize.

        Args:
            gamma: Gamma value. <1 = brighter, >1 = darker, 1.0 = no change.

        Example:
            >>> pipe = Pipeline().source("image_bytes").adjust_gamma(gamma=0.5)
        """
        return self._append_typed("adjust_gamma", {"gamma": gamma})

    def blur(self, sigma: FloatOrExpr) -> Pipeline:
        """Apply Gaussian blur.

        Args:
            sigma: Standard deviation for Gaussian kernel.
        """
        return self._append_typed("blur", {"sigma": sigma})

    def canny(
        self, *, low_threshold: FloatOrExpr = 50.0, high_threshold: FloatOrExpr = 150.0
    ) -> Pipeline:
        """Canny edge detection: Gaussian blur, Sobel gradients, non-maximum
        suppression and double-threshold hysteresis. Output is a U8 binary edge
        map (0 or 255).

        Args:
            low_threshold: Lower hysteresis threshold.
            high_threshold: Upper hysteresis threshold.

        Example:
            >>> edges = Pipeline().source("image_bytes").canny(low_threshold=50, high_threshold=150)
        """
        return self._append_typed(
            "canny", {"low_threshold": low_threshold, "high_threshold": high_threshold}
        )

    def cast(self, dtype: str) -> Pipeline:
        """Cast to a different data type.

        Args:
            dtype: Target data type (e.g., "f32", "u8").
        """
        return self._append_typed("cast", {"dtype": dtype})

    def ceil(self) -> Pipeline:
        """Round toward positive infinity. Domain: buffer → buffer."""
        return self._append_typed("ceil", {})

    def _clamp(self, min: FloatOrExpr, max: FloatOrExpr) -> Pipeline:
        """Clamp values to a range.

        The public `Pipeline.clamp` is sugar over this op that adds
        `out_dtype`/`preserve_dtype` (a trailing cast).

        Args:
            min: Minimum value (literal or expression).
            max: Maximum value (literal or expression).
        """
        return self._append_typed("clamp", {"min": min, "max": max})

    def clamp_max(self, value: FloatOrExpr) -> Pipeline:
        """Cap values at `value` (`min(x, value)`); one-sided clamp.

        Args:
            value: Upper bound (literal or per-row expression).
        """
        return self._append_typed("clamp_max", {"value": value})

    def clamp_min(self, value: FloatOrExpr) -> Pipeline:
        """Floor values at `value` (`max(x, value)`); one-sided clamp.

        Args:
            value: Lower bound (literal or per-row expression).
        """
        return self._append_typed("clamp_min", {"value": value})

    def crop(
        self,
        *,
        top: IntOrExpr = 0,
        left: IntOrExpr = 0,
        height: IntOrExpr | None = None,
        width: IntOrExpr | None = None,
    ) -> Pipeline:
        """Extract a rectangular region.

        Args:
            top: Top offset.
            left: Left offset.
            height: Crop height (None = to end).
            width: Crop width (None = to end).
        """
        return self._append_typed(
            "crop", {"top": top, "left": left, "height": height, "width": width}
        )

    def dilate(self, *, ksize: IntOrExpr = 3, iterations: IntOrExpr = 1) -> Pipeline:
        """Morphological dilation (local maximum over a `ksize × ksize` square). Requires single-channel input (e.g. after `.grayscale()` or `.threshold()`).

        Args:
            ksize: Size of the square structuring element. Must be odd and >= 1. Accepts
                a Polars expression for per-row dynamic values.
            iterations: Number of times the operation is applied. Accepts a Polars
                expression for per-row dynamic values.

        Example:
           >>> mask = Pipeline().source("image_bytes").grayscale().threshold(128).dilate(ksize=3)
        """
        return self._append_typed("dilate", {"ksize": ksize, "iterations": iterations})

    def equalize_histogram(self) -> Pipeline:
        """Apply histogram equalization for contrast enhancement: map each pixel
        through the normalized CDF, per channel. Output is U8.


        Example:
            >>> eq = Pipeline().source("image_bytes").grayscale().equalize_histogram()
        """
        return self._append_typed("equalize_histogram", {})

    def erode(self, *, ksize: IntOrExpr = 3, iterations: IntOrExpr = 1) -> Pipeline:
        """Morphological erosion (local minimum over a `ksize × ksize` square). Requires single-channel input (e.g. after `.grayscale()` or `.threshold()`).

        Args:
            ksize: Size of the square structuring element. Must be odd and >= 1. Accepts
                a Polars expression for per-row dynamic values.
            iterations: Number of times the operation is applied. Accepts a Polars
                expression for per-row dynamic values.

        Example:
           >>> mask = Pipeline().source("image_bytes").grayscale().threshold(128).erode(ksize=3)
        """
        return self._append_typed("erode", {"ksize": ksize, "iterations": iterations})

    def flip(self, axes: Sequence[int]) -> Pipeline:
        """Flip along specified axes.

        Args:
            axes: Axes to flip.
        """
        return self._append_typed("flip", {"axes": axes})

    def floor(self) -> Pipeline:
        """Round toward negative infinity. Domain: buffer → buffer."""
        return self._append_typed("floor", {})

    def grayscale(self) -> Pipeline:
        """Convert to grayscale (luminance 0.299R + 0.587G + 0.114B)."""
        return self._append_typed("grayscale", {})

    def histogram(
        self,
        bins: IntOrExpr | Sequence[float] = 256,
        range: Sequence[FloatOrExpr] | None = None,
        closed: str = "left",
        output: str = "buckets",
    ) -> Pipeline:
        """Compute pixel value histogram.

        Args:
            bins: Number of bins (default 256), a Polars expression for per-row dynamic
                bin count, or an explicit list of bin edges.
            range: (min, max) tuple. Auto-detected if None.
            closed: "left" or "right" interval inclusiveness (default "left").
            output: "buckets" (list of structs), "counts" (bin counts), "normalized"
                (sum to 1.0), "quantized" (pixel indices), "edges" (bin edges).

        Example:
            >>> Pipeline().source("image_bytes").grayscale().histogram(bins=8)
        """
        return self._append_typed(
            "histogram",
            {"bins": bins, "range": range, "closed": closed, "output": output},
        )

    def invert(self) -> Pipeline:
        """Invert pixel values: `255 - pixel` for u8, `1.0 - pixel` for float [0,1]."""
        return self._append_typed("invert", {})

    def letterbox(
        self,
        *,
        height: IntOrExpr,
        width: IntOrExpr,
        value: FloatOrExpr = 0.0,
        filter: str | pl.Expr = "lanczos3",
    ) -> Pipeline:
        """Resize image maintaining aspect ratio and pad to exact target size: fit
        within the target, then pad with centered positioning.

        Args:
            height: Target height (literal or expression).
            width: Target width (literal or expression).
            value: Fill value for padding (default 0, typically black). Accepts a Polars
                expression for per-row dynamic values.
            filter: Resampling filter for the resize step (default "lanczos3").

        Example:
            >>> pipe = Pipeline().source("image_bytes").letterbox(height=224, width=224)
        """
        return self._append_typed(
            "letterbox",
            {"height": height, "width": width, "value": value, "filter": filter},
        )

    def morphology_gradient(self, *, ksize: IntOrExpr = 3) -> Pipeline:
        """Morphological gradient (dilate - erode): an edge outline. Requires
        single-channel input.

        Args:
            ksize: Size of the square structuring element. Must be odd and >= 1. Accepts
                a Polars expression for per-row dynamic values.

        Example:
            >>> edges = Pipeline().source("image_bytes").grayscale().threshold(128).morphology_gradient(ksize=3)
        """
        return self._append_typed("morphology_gradient", {"ksize": ksize})

    def neg(self) -> Pipeline:
        """Negate every value (`-x`). Domain: buffer → buffer."""
        return self._append_typed("neg", {})

    def normalize(
        self,
        method: str = "minmax",
        mean: Sequence[FloatOrExpr] | None = None,
        std: Sequence[FloatOrExpr] | None = None,
        out_dtype: str | None = None,
    ) -> Pipeline:
        """Normalize values to a standard range.

        Args:
            method: Normalization method: "minmax" scales values to [0, 1] using per-
                element min/max; "zscore" standardizes to mean=0, std=1 using per-
                element statistics; "preset" applies ImageNet-style channel-wise
                normalization, `(x - mean[c]) / std[c]`, with the given `mean` and
                `std`.
            mean: Per-channel mean values; required for, and only valid with,
                method="preset" (e.g. ImageNet `[0.485, 0.456, 0.406]`). Each element
                may be a literal float or a Polars expression; the list length is the
                channel count.
            std: Per-channel standard deviation values; required for, and only valid
                with, method="preset" (e.g. ImageNet `[0.229, 0.224, 0.225]`). Each
                element accepts an expression, as with `mean`.
            out_dtype: Output dtype (default f32). Normalization computes in f32 and the
                result is cast to this dtype at execution. For half precision use the
                sink dtype instead (`.sink("numpy", dtype="f16")`).

        Example:
            >>> Pipeline().source().normalize(method="minmax")
            >>> Pipeline().source().normalize(
            ...     method="preset",
            ...     mean=[0.485, 0.456, 0.406],
            ...     std=[0.229, 0.224, 0.225],
            ... )
        """
        return self._append_typed(
            "normalize",
            {"method": method, "mean": mean, "std": std, "out_dtype": out_dtype},
        )

    def pad(
        self,
        *,
        top: IntOrExpr = 0,
        bottom: IntOrExpr = 0,
        left: IntOrExpr = 0,
        right: IntOrExpr = 0,
        value: FloatOrExpr = 0.0,
        mode: str | pl.Expr = "constant",
    ) -> Pipeline:
        """Add padding to the image.

        Args:
            top: Padding on top edge.
            bottom: Padding on bottom edge.
            left: Padding on left edge.
            right: Padding on right edge.
            value: Fill value for "constant" mode (default 0). Accepts a Polars
                expression for per-row dynamic values.
            mode: Padding mode - "constant", "edge", "reflect", "symmetric".

        Example:
            >>> pipe = Pipeline().source("image_bytes").pad(top=10, bottom=10)
            >>> pipe = Pipeline().source("image_bytes").pad(left=20, right=20, value=128)
        """
        return self._append_typed(
            "pad",
            {
                "top": top,
                "bottom": bottom,
                "left": left,
                "right": right,
                "value": value,
                "mode": mode,
            },
        )

    def pad_to_size(
        self,
        *,
        height: IntOrExpr,
        width: IntOrExpr,
        position: str | pl.Expr = "center",
        value: FloatOrExpr = 0.0,
    ) -> Pipeline:
        """Pad image to exact target size (computed at runtime). A larger image is
        not cropped - resize first if needed.

        Args:
            height: Target height.
            width: Target width.
            position: Where to place original content: "center" (default), "top-left" or
                "bottom-right".
            value: Fill value for padding (default 0). Accepts a Polars expression for
                per-row dynamic values.

        Example:
            >>> pipe = Pipeline().source("image_bytes").pad_to_size(height=100, width=200)
        """
        return self._append_typed(
            "pad_to_size",
            {"height": height, "width": width, "position": position, "value": value},
        )

    def reciprocal(self) -> Pipeline:
        """Reciprocal (`1 / x`; ±inf at zero). Domain: buffer → buffer."""
        return self._append_typed("reciprocal", {})

    def relu(self) -> Pipeline:
        """Apply ReLU activation (max(0, x)): negative values become zero."""
        return self._append_typed("relu", {})

    def reshape(self, shape: Sequence[IntOrExpr]) -> Pipeline:
        """Reshape array to new dimensions.

        Args:
            shape: New shape. The number of entries fixes the output rank; each entry
                may be a Polars expression.
        """
        return self._append_typed("reshape", {"shape": shape})

    def resize(
        self, *, height: IntOrExpr, width: IntOrExpr, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image to specified dimensions.

        Args:
            height: Target height.
            width: Target width.
            filter: Interpolation: "nearest", "bilinear", "lanczos3" (default).

        Example:
            >>> Pipeline().source("image_bytes").resize(height=224, width=224)
        """
        return self._append_typed(
            "resize", {"height": height, "width": width, "filter": filter}
        )

    def resize_max(
        self, max_size: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image so the maximum dimension equals target, preserving aspect ratio (200x100 with max_size=50 gives 50x25).

        Args:
            max_size: Target for the maximum dimension (literal or expression).
            filter: Resize filter ("nearest", "bilinear", "lanczos3").

        Example:
           >>> pipe = Pipeline().source("image_bytes").resize_max(224)
        """
        return self._append_typed(
            "resize_max", {"max_size": max_size, "filter": filter}
        )

    def resize_min(
        self, min_size: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image so the minimum dimension equals target, preserving aspect ratio (200x100 with min_size=50 gives 100x50).

        Args:
            min_size: Target for the minimum dimension (literal or expression).
            filter: Resize filter ("nearest", "bilinear", "lanczos3").

        Example:
           >>> pipe = Pipeline().source("image_bytes").resize_min(224)
        """
        return self._append_typed(
            "resize_min", {"min_size": min_size, "filter": filter}
        )

    def _resize_scale(
        self,
        *,
        scale_x: FloatOrExpr,
        scale_y: FloatOrExpr,
        filter: str | pl.Expr = "lanczos3",
    ) -> Pipeline:
        """Resize image by scale factor: `new_width = input_width * scale_x`,
        `new_height = input_height * scale_y`, computed at runtime.

        The public `Pipeline.resize_scale` is sugar over this op that also accepts
        one uniform `scale`.

        Args:
            scale_x: X (width) scale factor.
            scale_y: Y (height) scale factor.
            filter: Resize filter ("nearest", "bilinear", "lanczos3").
        """
        return self._append_typed(
            "resize_scale", {"scale_x": scale_x, "scale_y": scale_y, "filter": filter}
        )

    def resize_to_height(
        self, height: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image to target height, preserving aspect ratio (width is computed at runtime).

        Args:
            height: Target height (literal or expression).
            filter: Resize filter ("nearest", "bilinear", "lanczos3").

        Example:
           >>> pipe = Pipeline().source("image_bytes").resize_to_height(224)
        """
        return self._append_typed(
            "resize_to_height", {"height": height, "filter": filter}
        )

    def resize_to_width(
        self, width: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image to target width, preserving aspect ratio (height is computed at runtime).

        Args:
            width: Target width (literal or expression).
            filter: Resize filter ("nearest", "bilinear", "lanczos3").

        Example:
           >>> pipe = Pipeline().source("image_bytes").resize_to_width(224)
        """
        return self._append_typed("resize_to_width", {"width": width, "filter": filter})

    def round(self) -> Pipeline:
        """Round to nearest, ties to even (matches Polars/numpy). Domain: buffer → buffer."""
        return self._append_typed("round", {})

    def _scale(self, factor: FloatOrExpr) -> Pipeline:
        """Multiply all values by a factor.

        The public `Pipeline.scale` is sugar over this op that adds
        `out_dtype`/`preserve_dtype` (a trailing cast).

        Args:
            factor: Scale factor.
        """
        return self._append_typed("scale", {"factor": factor})

    def sign(self) -> Pipeline:
        """Sign: `-1`/`0`/`+1` (`0` for ±0, NaN for NaN). Domain: buffer → buffer."""
        return self._append_typed("sign", {})

    def sqrt(self) -> Pipeline:
        """Square root (`sqrt(x)`; NaN for negative input). Domain: buffer → buffer."""
        return self._append_typed("sqrt", {})

    def square(self) -> Pipeline:
        """Square (`x * x`). Domain: buffer → buffer."""
        return self._append_typed("square", {})

    def subtract_constant(self, value: FloatOrExpr) -> Pipeline:
        """Subtract a constant from every value (`x - value`).

        Args:
            value: Constant subtrahend (literal or per-row expression).
        """
        return self._append_typed("subtract_constant", {"value": value})

    def threshold(self, value: FloatOrExpr) -> Pipeline:
        """Apply binary threshold: a U8 mask, 255 where the element exceeds `value`
        and 0 elsewhere (for u8 input typically 0-255; for [0, 1] floats e.g. 0.5).

        Args:
            value: Threshold value (int or float, or Polars expression).
        """
        return self._append_typed("threshold", {"value": value})

    def transpose(self, axes: Sequence[int]) -> Pipeline:
        """Transpose dimensions.

        Args:
            axes: New order of axes: a permutation of every input axis.
        """
        return self._append_typed("transpose", {"axes": axes})

    def trunc(self) -> Pipeline:
        """Round toward zero (drop the fractional part). Domain: buffer → buffer."""
        return self._append_typed("trunc", {})

    def warp_affine(
        self,
        matrix: Sequence[FloatOrExpr],
        output_size: Sequence[IntOrExpr],
        *,
        interpolation: str | pl.Expr = "bilinear",
        border_value: FloatOrExpr = 0.0,
    ) -> Pipeline:
        """Apply a 2x3 affine transformation matrix.

        The matrix ``[a, b, tx, c, d, ty]`` is a **forward** mapping from
        source to destination (same convention as OpenCV ``warpAffine``)::

            x_dst = a * x_src + b * y_src + tx
            y_dst = c * x_src + d * y_src + ty

        The kernel inverts this matrix internally for interpolation.

        Domain: buffer → buffer

        Args:
            matrix: Six-element sequence representing the 2x3 affine matrix ``[a, b, tx,
                c, d, ty]`` (forward mapping). **Each element may be a literal float or
                a Polars expression**, so a batch can apply a different (e.g. random)
                affine per row in one call — the matrix is resolved per row at
                execution.
            output_size: ``(height, width)`` of the output image. Each element accepts a
                Polars expression for per-row dynamic values.
            interpolation: Interpolation method -- ``"bilinear"`` (default) or
                ``"nearest"``.
            border_value: Pixel value for out-of-bounds regions (default 0).

        Example:
            ```python
            >>> # Translate image by (50, 30)
            >>> pipe = Pipeline().source("image_bytes").warp_affine(
            ...     matrix=[1.0, 0.0, 50.0, 0.0, 1.0, 30.0],
            ...     output_size=(224, 224),
            ... )
            >>>
            >>> # Per-sample random affine: each row uses its own matrix columns
            >>> pipe = Pipeline().source("image_bytes").warp_affine(
            ...     matrix=[pl.col("a"), pl.col("b"), pl.col("tx"),
            ...             pl.col("c"), pl.col("d"), pl.col("ty")],
            ...     output_size=(224, 224),
            ... )
            ```
        """
        return self._append_typed(
            "warp_affine",
            {
                "matrix": matrix,
                "output_size": output_size,
                "interpolation": interpolation,
                "border_value": border_value,
            },
        )
