# This file is generated by scripts/gen_ops.py from tests/golden/op_catalog.json,
# io_catalog.json, enum_catalog.json and pass_catalog.json. Do not edit by hand: change the Rust
# definition (src/ops/, src/formats/), re-bless the catalogues
# (POLARS_CV_BLESS=1 cargo test -p polars-cv catalog_matches), then rerun the
# generator.
"""Builder methods generated from the typed op catalogue."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import polars as pl

    from polars_cv._types import BoolOrExpr, FloatOrExpr, IntOrExpr
    from polars_cv.lazy import LazyPipelineExpr
    from polars_cv.pipeline import Pipeline


class ApproxMethod(str, Enum):
    """Contour point-approximation method for ``extract_contours``.

    - NONE: Keep every boundary point.
    - SIMPLE: Drop redundant collinear points (default).
    - APPROX: Douglas-Peucker style approximation.
    """

    NONE = "none"
    SIMPLE = "simple"
    APPROX = "approx"


class BorderMode(str, Enum):
    """Border-handling mode for 2D convolution (``convolve2d``).

    - REPLICATE: Replicate the nearest edge pixel.
    - ZERO: Treat out-of-bounds pixels as zero.
    - REFLECT: Reflect pixels around the edge (dcba|abcd|dcba).
    """

    REPLICATE = "replicate"
    ZERO = "zero"
    REFLECT = "reflect"


class ColorSpace(str, Enum):
    """Supported color spaces for ``convert_color``."""

    RGB = "rgb"
    BGR = "bgr"
    HSV = "hsv"
    LAB = "lab"
    YCBCR = "ycbcr"
    GRAY = "gray"


class DType(str, Enum):
    """Supported data types."""

    U8 = "u8"
    I8 = "i8"
    U16 = "u16"
    I16 = "i16"
    U32 = "u32"
    I32 = "i32"
    U64 = "u64"
    I64 = "i64"
    F32 = "f32"
    F64 = "f64"


class Domain(str, Enum):
    """The kind of data a pipeline carries at one point: ``buffer`` (an image or array), ``contour`` (geometry), ``scalar`` or ``vector``."""

    BUFFER = "buffer"
    CONTOUR = "contour"
    SCALAR = "scalar"
    VECTOR = "vector"


class ExtractMode(str, Enum):
    """Contour retrieval mode for ``extract_contours``.

    - EXTERNAL: Outermost contours only (default).
    - TREE: Full nesting hierarchy.
    - ALL: Every contour, without hierarchy.
    """

    EXTERNAL = "external"
    TREE = "tree"
    ALL = "all"


class FetchErrorPolicy(str, Enum):
    """What an unreadable path does to the query.

    Settled at fetch time, before any graph node runs, which is why it is not
    :class:`RowErrorPolicy`: ``.cv.read_bytes()`` has no graph at all, and
    ``source("file_path")`` resolves its bytes before the graph starts.
    - RAISE: an unreadable path fails the whole query.
    - NULL: an unreadable path yields null for that row only.
    """

    RAISE = "raise"
    NULL = "null"


class FilterType(str, Enum):
    """Image resize filter types."""

    NEAREST = "nearest"
    BILINEAR = "bilinear"
    CATMULLROM = "catmullrom"
    GAUSSIAN = "gaussian"
    LANCZOS3 = "lanczos3"


class HashAlgorithm(str, Enum):
    """Perceptual hash algorithm selection.

    Different algorithms trade off speed vs robustness to transformations:
    - AVERAGE: Fastest, least robust. Good for exact/near-exact matches.
    - DIFFERENCE: Gradient-based, good balance of speed and robustness.
    - PERCEPTUAL: DCT-based, most robust to resize/compression. Recommended default.
    - BLOCKHASH: Block-based, good resistance to cropping.
    """

    AVERAGE = "average"
    DIFFERENCE = "difference"
    PERCEPTUAL = "perceptual"
    BLOCKHASH = "blockhash"


class HistogramClosed(str, Enum):
    """Interval inclusiveness for histogram binning.

    - LEFT: Intervals are left-closed ``[a, b)``.
    - RIGHT: Intervals are right-closed ``(a, b]``.
    """

    LEFT = "left"
    RIGHT = "right"


class HistogramOutput(str, Enum):
    """Histogram output mode selection.

    Controls what the histogram operation returns:
    - COUNTS: Bin counts as a 1D array
    - NORMALIZED: Histogram normalized to sum to 1.0
    - QUANTIZED: Input array with pixels replaced by bin indices
    - EDGES: Bin edge values
    - BUCKETS: List of bucket structs (lower_edge, upper_edge, count, normalized)
    """

    COUNTS = "counts"
    NORMALIZED = "normalized"
    QUANTIZED = "quantized"
    EDGES = "edges"
    BUCKETS = "buckets"


class InterpolationType(str, Enum):
    """Interpolation used when sampling an affine warp (``rotate``,
    ``warp_affine``, ``shear``, ``rotate_and_scale``).

    - NEAREST: Nearest-neighbour sampling (preserves hard edges/pixel art).
    - BILINEAR: Bilinear sampling (default).
    """

    NEAREST = "nearest"
    BILINEAR = "bilinear"


class LabelReduction(str, Enum):
    """Reduction over a contour region's pixel values (``label_reduce``)."""

    MAX = "max"
    MEAN = "mean"
    SUM = "sum"


class LabelRegionMode(str, Enum):
    """Region selection for ``label_reduce``.

    - INTERIOR: Pixels strictly inside the contour polygon.
    - BOUNDARY: Interior pixels plus pixels on the contour boundary.
    - BBOX: All pixels within the bounding box.
    """

    INTERIOR = "interior"
    BOUNDARY = "boundary"
    BBOX = "bbox"


class LogicalPass(str, Enum):
    """A logical optimisation pass (``OptFlags`` field names)."""

    COMMON_SUBEXPRESSION_ELIMINATION = "common_subexpression_elimination"
    IDENTITY_ELIMINATION = "identity_elimination"
    SPATIAL_WINDOW_PUSHDOWN = "spatial_window_pushdown"


class NormalizeMethod(str, Enum):
    """Normalization methods (``PRESET``: channel-wise with preset mean/std values)."""

    MINMAX = "minmax"
    ZSCORE = "zscore"
    PRESET = "preset"


class NullParamPolicy(str, Enum):
    """What a null in a per-row expression parameter means.

    Deliberately separate from :class:`RowErrorPolicy`: under ``NULL`` a null
    parameter is not an error, so it records no ``_error`` message and does not
    weaken reporting for genuine decode/encode/operation failures.
    - RAISE: a null parameter fails the expression.
    - NULL: the affected node produces no output for that row.
    """

    RAISE = "raise"
    NULL = "null"


class PadMode(str, Enum):
    """Padding mode selection.

    Controls how padding values are determined:
    - CONSTANT: Fill with a constant value (default)
    - EDGE: Replicate edge values
    - REFLECT: Reflect values at edge (not including edge)
    - SYMMETRIC: Reflect values at edge (including edge)
    """

    CONSTANT = "constant"
    EDGE = "edge"
    REFLECT = "reflect"
    SYMMETRIC = "symmetric"


class PadPosition(str, Enum):
    """Position for pad_to_size.

    Controls where the original content is placed:
    - CENTER: Center content in padded area (default)
    - TOP_LEFT: Place content at top-left corner
    - BOTTOM_RIGHT: Place content at bottom-right corner
    """

    CENTER = "center"
    TOP_LEFT = "top-left"
    BOTTOM_RIGHT = "bottom-right"


class RowErrorPolicy(str, Enum):
    """What a failing row does to a graph query.

    Applies to errors raised while producing a row — source decode, op
    execution, output encode:
    - RAISE: propagate the first error, failing the whole expression.
    - NULL: a failing row yields null; other rows proceed.
    - NULL_WITH_MESSAGE: as NULL, plus an `_error` field.
    """

    RAISE = "raise"
    NULL = "null"
    NULL_WITH_MESSAGE = "null_with_message"


class ScaleOrigin(str, Enum):
    """Point a contour scale operation is measured from (``.contour.scale``)."""

    CENTROID = "centroid"
    BBOX_CENTER = "bbox_center"
    ORIGIN = "origin"


class Winding(str, Enum):
    """Winding direction of a contour ring (``.contour.ensure_winding``).

    Long spellings included: the plugin has always accepted
    ``"clockwise"``/``"counterclockwise"`` alongside the short forms.
    """

    CCW = "ccw"
    COUNTERCLOCKWISE = "counterclockwise"
    CW = "cw"
    CLOCKWISE = "clockwise"


class SourceFormat(str, Enum):
    """Every source format (typed per format in ``src/formats/``)."""

    ARRAY = "array"
    AUTO = "auto"
    BLOB = "blob"
    CONTOUR = "contour"
    FILE_PATH = "file_path"
    IMAGE_BYTES = "image_bytes"
    LIST = "list"
    RAW = "raw"


class SinkFormat(str, Enum):
    """Every sink format (typed per format in ``src/formats/``)."""

    ARRAY = "array"
    BLOB = "blob"
    JPEG = "jpeg"
    LIST = "list"
    NATIVE = "native"
    NDARRAY = "ndarray"
    NUMPY = "numpy"
    PNG = "png"
    TIFF = "tiff"
    TORCH = "torch"
    WEBP = "webp"


#: Ops whose wire form is typed (bare values and slots).
TYPED_OPS: frozenset[str] = frozenset(
    [
        "abs",
        "add",
        "add_constant",
        "adjust_contrast",
        "adjust_gamma",
        "apply_mask",
        "assert_shape",
        "bitwise_and",
        "bitwise_or",
        "bitwise_xor",
        "blend",
        "blur",
        "canny",
        "cast",
        "ceil",
        "channel_merge",
        "channel_select",
        "channel_swap",
        "clamp",
        "clamp_max",
        "clamp_min",
        "contour_area",
        "contour_bounding_box",
        "contour_centroid",
        "contour_convex_hull",
        "contour_perimeter",
        "contour_scale",
        "contour_simplify",
        "contour_translate",
        "convolve2d",
        "crop",
        "cvt_color",
        "dilate",
        "divide",
        "equalize_histogram",
        "erode",
        "extract_contours",
        "extract_shape",
        "flip",
        "floor",
        "grayscale",
        "histogram",
        "invert",
        "label_reduce",
        "letterbox",
        "maximum",
        "minimum",
        "morphology_gradient",
        "multiply",
        "neg",
        "normalize",
        "pad",
        "pad_to_size",
        "perceptual_hash",
        "rasterize",
        "ratio",
        "reciprocal",
        "reduce_argmax",
        "reduce_argmin",
        "reduce_max",
        "reduce_mean",
        "reduce_min",
        "reduce_percentile",
        "reduce_popcount",
        "reduce_std",
        "reduce_sum",
        "relu",
        "reshape",
        "resize",
        "resize_max",
        "resize_min",
        "resize_scale",
        "resize_to_height",
        "resize_to_width",
        "rotate",
        "round",
        "scale",
        "sign",
        "sqrt",
        "square",
        "subtract",
        "subtract_constant",
        "threshold",
        "transpose",
        "trunc",
        "warp_affine",
    ]
)

#: Every optimisation pass, in the order they apply: (name, tier, summary).
PASS_CATALOG: tuple[tuple[str, str, str], ...] = (
    (
        "common_subexpression_elimination",
        "logical",
        "Share a common leading op run across sibling pipelines that read the same source column into one upstream node.",
    ),
    (
        "identity_elimination",
        "logical",
        "Delete no-op operations — a zero pad, a same-dtype cast, a full-frame crop — that preserve their input byte for byte.",
    ),
    (
        "spatial_window_pushdown",
        "logical",
        "Hoist a spatial window (a crop/ROI) earlier past ops it commutes with, so upstream ops process fewer pixels.",
    ),
    (
        "cast_chain_collapse",
        "engine",
        "Drop a redundant intermediate cast from a cast chain when the intermediate dtype losslessly holds the input and dropping it keeps the final cast's conversion (a narrowing intermediate quantizes, and a float between an integer input and an integer target saturates, so both are kept).",
    ),
    (
        "cast_identity",
        "engine",
        "Drop a cast whose target dtype already equals its input dtype.",
    ),
    (
        "view_flip_involution",
        "engine",
        "Cancel two adjacent flips over the same axes (flip∘flip = id).",
    ),
    (
        "view_transpose_merge",
        "engine",
        "Merge two adjacent transposes into one (or into the identity).",
    ),
    (
        "scalar_fusion",
        "engine",
        "Fuse adjacent scalar/compute ops into one kernel (f64 chains stay unfused — a mandatory precision guard, not this toggle).",
    ),
)


@dataclass(frozen=True)
class _OptFlagFields:
    """One boolean per optimisation pass, in catalogue order."""

    common_subexpression_elimination: bool = True
    identity_elimination: bool = True
    spatial_window_pushdown: bool = True
    cast_chain_collapse: bool = True
    cast_identity: bool = True
    view_flip_involution: bool = True
    view_transpose_merge: bool = True
    scalar_fusion: bool = True


#: Each typed op's field types, as the catalogue describes them.
OP_FIELDS: dict[str, dict[str, Any]] = {
    "abs": {},
    "add": {"other": {"kind": "node"}},
    "add_constant": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "adjust_contrast": {"factor": {"kind": "scalar", "per_row": True, "py": "float"}},
    "adjust_gamma": {"gamma": {"kind": "scalar", "per_row": True, "py": "float"}},
    "apply_mask": {
        "mask": {"kind": "node"},
        "invert": {"kind": "scalar", "per_row": True, "py": "bool"},
    },
    "assert_shape": {
        "rank": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        },
        "dims": {
            "kind": "array",
            "len": 3,
            "inner": {
                "kind": "optional",
                "inner": {"kind": "scalar", "per_row": True, "py": "int"},
            },
        },
    },
    "bitwise_and": {"other": {"kind": "node"}},
    "bitwise_or": {"other": {"kind": "node"}},
    "bitwise_xor": {"other": {"kind": "node"}},
    "blend": {"other": {"kind": "node"}},
    "blur": {"sigma": {"kind": "scalar", "per_row": True, "py": "float"}},
    "canny": {
        "low_threshold": {"kind": "scalar", "per_row": True, "py": "float"},
        "high_threshold": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "cast": {
        "dtype": {
            "kind": "scalar",
            "per_row": False,
            "py": "DType",
            "variants": [
                "u8",
                "i8",
                "u16",
                "i16",
                "u32",
                "i32",
                "u64",
                "i64",
                "f32",
                "f64",
            ],
        }
    },
    "ceil": {},
    "channel_merge": {"others": {"kind": "list", "inner": {"kind": "node"}}},
    "channel_select": {"index": {"kind": "scalar", "per_row": True, "py": "int"}},
    "channel_swap": {
        "order": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        }
    },
    "clamp": {
        "min": {"kind": "scalar", "per_row": True, "py": "float"},
        "max": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "clamp_max": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "clamp_min": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "contour_area": {"signed": {"kind": "scalar", "per_row": True, "py": "bool"}},
    "contour_bounding_box": {},
    "contour_centroid": {},
    "contour_convex_hull": {},
    "contour_perimeter": {},
    "contour_scale": {
        "sx": {"kind": "scalar", "per_row": True, "py": "float"},
        "sy": {"kind": "scalar", "per_row": True, "py": "float"},
        "origin": {
            "kind": "scalar",
            "per_row": True,
            "py": "ScaleOrigin",
            "variants": ["centroid", "bbox_center", "origin"],
        },
    },
    "contour_simplify": {
        "tolerance": {"kind": "scalar", "per_row": True, "py": "float"}
    },
    "contour_translate": {
        "dx": {"kind": "scalar", "per_row": True, "py": "float"},
        "dy": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "convolve2d": {
        "kernel": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": True, "py": "float"},
        },
        "ksize": {"kind": "scalar", "per_row": True, "py": "int"},
        "normalize": {"kind": "scalar", "per_row": True, "py": "bool"},
        "border": {
            "kind": "scalar",
            "per_row": True,
            "py": "BorderMode",
            "variants": ["replicate", "zero", "reflect"],
        },
    },
    "crop": {
        "top": {"kind": "scalar", "per_row": True, "py": "int"},
        "left": {"kind": "scalar", "per_row": True, "py": "int"},
        "height": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
        "width": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
    },
    "cvt_color": {
        "from_space": {
            "kind": "scalar",
            "per_row": False,
            "py": "ColorSpace",
            "variants": ["rgb", "bgr", "hsv", "lab", "ycbcr", "gray"],
        },
        "to_space": {
            "kind": "scalar",
            "per_row": False,
            "py": "ColorSpace",
            "variants": ["rgb", "bgr", "hsv", "lab", "ycbcr", "gray"],
        },
    },
    "dilate": {
        "ksize": {"kind": "scalar", "per_row": True, "py": "int"},
        "iterations": {"kind": "scalar", "per_row": True, "py": "int"},
    },
    "divide": {"other": {"kind": "node"}},
    "equalize_histogram": {},
    "erode": {
        "ksize": {"kind": "scalar", "per_row": True, "py": "int"},
        "iterations": {"kind": "scalar", "per_row": True, "py": "int"},
    },
    "extract_contours": {
        "mode": {
            "kind": "scalar",
            "per_row": True,
            "py": "ExtractMode",
            "variants": ["external", "tree", "all"],
        },
        "method": {
            "kind": "scalar",
            "per_row": True,
            "py": "ApproxMethod",
            "variants": ["none", "simple", "approx"],
        },
        "min_area": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": True, "py": "float"},
        },
    },
    "extract_shape": {},
    "flip": {
        "axes": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "floor": {},
    "grayscale": {},
    "histogram": {
        "bins": {
            "kind": "one_of",
            "options": [
                {"kind": "scalar", "per_row": True, "py": "int"},
                {
                    "kind": "list",
                    "inner": {"kind": "scalar", "per_row": False, "py": "float"},
                },
            ],
        },
        "range": {
            "kind": "optional",
            "inner": {
                "kind": "array",
                "len": 2,
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "closed": {
            "kind": "scalar",
            "per_row": False,
            "py": "HistogramClosed",
            "variants": ["left", "right"],
        },
        "output": {
            "kind": "scalar",
            "per_row": False,
            "py": "HistogramOutput",
            "variants": ["counts", "normalized", "quantized", "edges", "buckets"],
        },
    },
    "invert": {},
    "label_reduce": {
        "contours": {"kind": "column"},
        "reduction": {
            "kind": "scalar",
            "per_row": True,
            "py": "LabelReduction",
            "variants": ["max", "mean", "sum"],
        },
        "region_mode": {
            "kind": "scalar",
            "per_row": True,
            "py": "LabelRegionMode",
            "variants": ["interior", "boundary", "bbox"],
        },
    },
    "letterbox": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "value": {"kind": "scalar", "per_row": True, "py": "float"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "maximum": {"other": {"kind": "node"}},
    "minimum": {"other": {"kind": "node"}},
    "morphology_gradient": {"ksize": {"kind": "scalar", "per_row": True, "py": "int"}},
    "multiply": {"other": {"kind": "node"}},
    "neg": {},
    "normalize": {
        "method": {
            "kind": "scalar",
            "per_row": False,
            "py": "NormalizeMethod",
            "variants": ["minmax", "zscore", "preset"],
        },
        "mean": {
            "kind": "optional",
            "inner": {
                "kind": "list",
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "std": {
            "kind": "optional",
            "inner": {
                "kind": "list",
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "out_dtype": {
            "kind": "optional",
            "inner": {
                "kind": "scalar",
                "per_row": False,
                "py": "DType",
                "variants": [
                    "u8",
                    "i8",
                    "u16",
                    "i16",
                    "u32",
                    "i32",
                    "u64",
                    "i64",
                    "f32",
                    "f64",
                ],
            },
        },
    },
    "pad": {
        "top": {"kind": "scalar", "per_row": True, "py": "int"},
        "bottom": {"kind": "scalar", "per_row": True, "py": "int"},
        "left": {"kind": "scalar", "per_row": True, "py": "int"},
        "right": {"kind": "scalar", "per_row": True, "py": "int"},
        "value": {"kind": "scalar", "per_row": True, "py": "float"},
        "mode": {
            "kind": "scalar",
            "per_row": True,
            "py": "PadMode",
            "variants": ["constant", "edge", "reflect", "symmetric"],
        },
    },
    "pad_to_size": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "position": {
            "kind": "scalar",
            "per_row": True,
            "py": "PadPosition",
            "variants": ["center", "top-left", "bottom-right"],
        },
        "value": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "perceptual_hash": {
        "algorithm": {
            "kind": "scalar",
            "per_row": False,
            "py": "HashAlgorithm",
            "variants": ["average", "difference", "perceptual", "blockhash"],
        },
        "hash_size": {"kind": "scalar", "per_row": False, "py": "int"},
    },
    "rasterize": {
        "size": {
            "kind": "one_of",
            "options": [
                {
                    "kind": "array",
                    "len": 2,
                    "inner": {"kind": "scalar", "per_row": True, "py": "int"},
                },
                {"kind": "node"},
            ],
        },
        "fill_value": {"kind": "scalar", "per_row": True, "py": "int"},
        "background": {"kind": "scalar", "per_row": True, "py": "int"},
    },
    "ratio": {"other": {"kind": "node"}},
    "reciprocal": {},
    "reduce_argmax": {"axis": {"kind": "scalar", "per_row": False, "py": "int"}},
    "reduce_argmin": {"axis": {"kind": "scalar", "per_row": False, "py": "int"}},
    "reduce_max": {
        "axis": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "reduce_mean": {
        "axis": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "reduce_min": {
        "axis": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "reduce_percentile": {"q": {"kind": "scalar", "per_row": True, "py": "float"}},
    "reduce_popcount": {},
    "reduce_std": {
        "axis": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        },
        "ddof": {"kind": "scalar", "per_row": True, "py": "int"},
    },
    "reduce_sum": {},
    "relu": {},
    "reshape": {
        "shape": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        }
    },
    "resize": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_max": {
        "max_size": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_min": {
        "min_size": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_scale": {
        "scale_x": {"kind": "scalar", "per_row": True, "py": "float"},
        "scale_y": {"kind": "scalar", "per_row": True, "py": "float"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_to_height": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "resize_to_width": {
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "rotate": {
        "angle": {"kind": "scalar", "per_row": True, "py": "float"},
        "expand": {"kind": "scalar", "per_row": False, "py": "bool"},
        "interpolation": {
            "kind": "scalar",
            "per_row": True,
            "py": "InterpolationType",
            "variants": ["nearest", "bilinear"],
        },
        "border_value": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "round": {},
    "scale": {"factor": {"kind": "scalar", "per_row": True, "py": "float"}},
    "sign": {},
    "sqrt": {},
    "square": {},
    "subtract": {"other": {"kind": "node"}},
    "subtract_constant": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "threshold": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "transpose": {
        "axes": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "trunc": {},
    "warp_affine": {
        "matrix": {
            "kind": "array",
            "len": 6,
            "inner": {"kind": "scalar", "per_row": True, "py": "float"},
        },
        "output_size": {
            "kind": "array",
            "len": 2,
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
        "interpolation": {
            "kind": "scalar",
            "per_row": True,
            "py": "InterpolationType",
            "variants": ["nearest", "bilinear"],
        },
        "border_value": {"kind": "scalar", "per_row": True, "py": "float"},
    },
}


class _OpsMixin:
    """The generated builder methods ``Pipeline`` inherits."""

    if TYPE_CHECKING:

        def _append_typed(self, op_name: str, values: dict[str, Any]) -> Pipeline: ...

    def abs(self) -> Pipeline:
        """Absolute value (`|x|`). Domain: buffer → buffer."""
        return self._append_typed("abs", {})

    def add_constant(self, value: FloatOrExpr) -> Pipeline:
        """Add a constant to every value (`x + value`).

        Args:
            value: Constant addend (literal or per-row expression).
        """
        return self._append_typed("add_constant", {"value": value})

    def adjust_contrast(self, factor: FloatOrExpr) -> Pipeline:
        """Adjust image contrast: `(pixel - mean) * factor + mean`.

        Args:
            factor: Contrast factor. 1.0 = no change, >1 = more contrast, <1 = less.

        Example:
            >>> pipe = Pipeline().source("image_bytes").adjust_contrast(factor=1.5)
        """
        return self._append_typed("adjust_contrast", {"factor": factor})

    def adjust_gamma(self, gamma: FloatOrExpr) -> Pipeline:
        """Apply gamma (power-law) correction: normalize to [0,1], raise to `gamma`,
        denormalize.

        Args:
            gamma: Gamma value. <1 = brighter, >1 = darker, 1.0 = no change.

        Example:
            >>> pipe = Pipeline().source("image_bytes").adjust_gamma(gamma=0.5)
        """
        return self._append_typed("adjust_gamma", {"gamma": gamma})

    def _assert_shape(
        self, dims: Sequence[IntOrExpr | None], *, rank: int | None = None
    ) -> Pipeline:
        """Declare the shape of the data at this point: its rank and any of the sizes
        of dimensions 0, 1 and 2.

        The planner applies the declaration (refusing one it contradicts), and
        execution checks it against every row, so everything downstream rests on a
        checked fact. The public `Pipeline.assert_shape` is sugar over this op.

        Args:
            rank: The rank, when declared (`assert_shape(dims=[...])` declares
                `len(dims)`).
            dims: The sizes of dimensions 0, 1 and 2; `None` declares nothing about that
                dimension. A per-row size is checked per row and is no plan-time fact.
        """
        return self._append_typed("assert_shape", {"rank": rank, "dims": dims})

    def blur(self, sigma: FloatOrExpr) -> Pipeline:
        """Apply Gaussian blur.

        Args:
            sigma: Standard deviation for Gaussian kernel.
        """
        return self._append_typed("blur", {"sigma": sigma})

    def canny(
        self, *, low_threshold: FloatOrExpr = 50.0, high_threshold: FloatOrExpr = 150.0
    ) -> Pipeline:
        """Canny edge detection: Gaussian blur, Sobel gradients, non-maximum
        suppression and double-threshold hysteresis. Output is a U8 binary edge
        map (0 or 255).

        Args:
            low_threshold: Lower hysteresis threshold.
            high_threshold: Upper hysteresis threshold.

        Example:
            >>> edges = Pipeline().source("image_bytes").canny(low_threshold=50, high_threshold=150)
        """
        return self._append_typed(
            "canny", {"low_threshold": low_threshold, "high_threshold": high_threshold}
        )

    def cast(self, dtype: str) -> Pipeline:
        """Cast to a different data type.

        Args:
            dtype: Target data type (e.g., "f32", "u8").
        """
        return self._append_typed("cast", {"dtype": dtype})

    def ceil(self) -> Pipeline:
        """Round toward positive infinity. Domain: buffer → buffer."""
        return self._append_typed("ceil", {})

    def channel_select(self, index: IntOrExpr) -> Pipeline:
        """Extract a single channel from a multi-channel image: a 2D [H, W] buffer
        from a [H, W, C] input.

        Args:
            index: Channel index to extract (0-based). Accepts a Polars expression for
                per-row dynamic selection.

        Example:
            >>> pipe = Pipeline().source("image_bytes").channel_select(index=0)  # Red channel
        """
        return self._append_typed("channel_select", {"index": index})

    def channel_swap(self, order: Sequence[IntOrExpr]) -> Pipeline:
        """Reorder channels in a multi-channel image.

        Args:
            order: New channel ordering, e.g. [2, 1, 0] for RGB-to-BGR. **Each index may
                be a literal or a Polars expression**, so the permutation can vary per
                row. The list *length* is the channel count and must be literal.

        Example:
            >>> pipe = Pipeline().source("image_bytes").channel_swap(order=[2, 1, 0])
        """
        return self._append_typed("channel_swap", {"order": order})

    def _clamp(self, *, min: FloatOrExpr, max: FloatOrExpr) -> Pipeline:
        """Clamp values to a range.

        The public `Pipeline.clamp` is sugar over this op that adds
        `out_dtype`/`preserve_dtype` (a trailing cast).

        Args:
            min: Minimum value (literal or expression).
            max: Maximum value (literal or expression).
        """
        return self._append_typed("clamp", {"min": min, "max": max})

    def clamp_max(self, value: FloatOrExpr) -> Pipeline:
        """Cap values at `value` (`min(x, value)`); one-sided clamp.

        Args:
            value: Upper bound (literal or per-row expression).
        """
        return self._append_typed("clamp_max", {"value": value})

    def clamp_min(self, value: FloatOrExpr) -> Pipeline:
        """Floor values at `value` (`max(x, value)`); one-sided clamp.

        Args:
            value: Lower bound (literal or per-row expression).
        """
        return self._append_typed("clamp_min", {"value": value})

    def area(self, *, signed: BoolOrExpr = False) -> Pipeline:
        """Compute the area of the contour using the Shoelace formula.

        Domain transition: contour → scalar

        Args:
            signed: If True, return signed area (negative for CW winding).
        """
        return self._append_typed("contour_area", {"signed": signed})

    def bounding_box(self) -> Pipeline:
        """Compute the axis-aligned bounding box of the contour.

        Domain transition: contour → vector (returns [x, y, width, height])
        """
        return self._append_typed("contour_bounding_box", {})

    def centroid(self) -> Pipeline:
        """Compute the centroid (center of mass) of the contour.

        Domain transition: contour → vector (returns [x, y])
        """
        return self._append_typed("contour_centroid", {})

    def convex_hull(self) -> Pipeline:
        """Compute the convex hull of the contour.

        Domain: contour → contour
        """
        return self._append_typed("contour_convex_hull", {})

    def perimeter(self) -> Pipeline:
        """Compute the perimeter (arc length) of the contour.

        Domain transition: contour → scalar
        """
        return self._append_typed("contour_perimeter", {})

    def _scale_contour(
        self, *, sx: FloatOrExpr, sy: FloatOrExpr, origin: str | pl.Expr = "centroid"
    ) -> Pipeline:
        """Scale the contour about *origin*.

        Domain: contour → contour

        Args:
            sx: X scale factor.
            sy: Y scale factor.
            origin: Point to scale about — ``"centroid"`` (the default),
                ``"bbox_center"`` or ``"origin"``. Accepts an expression for a per-row
                choice: which point the scale is measured from changes no output shape,
                rank or dtype, so it meets the eligibility rule for a per-row parameter.

        Note:
            The default is ``"centroid"``, which is what this method has always
            done — it previously hardcoded it with no way to choose. The
            ``.contour.scale`` accessor defaults to ``"origin"`` instead; pass
            *origin* explicitly if you need the two to agree.
        """
        return self._append_typed(
            "contour_scale", {"sx": sx, "sy": sy, "origin": origin}
        )

    def simplify(self, tolerance: FloatOrExpr) -> Pipeline:
        """Simplify the contour using the Douglas-Peucker algorithm.

        Domain: contour → contour

        Args:
            tolerance: Maximum distance from the original contour.
        """
        return self._append_typed("contour_simplify", {"tolerance": tolerance})

    def translate(self, *, dx: FloatOrExpr, dy: FloatOrExpr) -> Pipeline:
        """Translate the contour by an offset.

        Domain: contour → contour

        Args:
            dx: X offset (horizontal translation).
            dy: Y offset (vertical translation).
        """
        return self._append_typed("contour_translate", {"dx": dx, "dy": dy})

    def convolve2d(
        self,
        *,
        kernel: Sequence[FloatOrExpr],
        ksize: IntOrExpr,
        normalize: BoolOrExpr = False,
        border: str | pl.Expr = "replicate",
    ) -> Pipeline:
        """Apply generic 2D convolution with an arbitrary kernel.

        Domain: buffer → buffer

        Args:
            kernel: Flattened kernel values (row-major, ``ksize × ksize``). **Each
                coefficient may be a literal float or a Polars expression**, so a batch
                can convolve with a different kernel per row. The kernel *length* is
                structural and must be a literal odd square.
            ksize: Kernel dimension (must be odd; kernel is ``ksize × ksize``). Accepts
                a Polars expression for per-row dynamic values.
            normalize: If True, divide output by the sum of absolute kernel values.
            border: Border handling mode (``"replicate"``, ``"zero"``, ``"reflect"``).

        Example:
            ```python
            >>> edge = Pipeline().source("image_bytes").convolve2d(
            ...     kernel=[-1, -1, -1, -1, 8, -1, -1, -1, -1],
            ...     ksize=3,
            ... )
            ```
        """
        return self._append_typed(
            "convolve2d",
            {
                "kernel": kernel,
                "ksize": ksize,
                "normalize": normalize,
                "border": border,
            },
        )

    def crop(
        self,
        *,
        top: IntOrExpr = 0,
        left: IntOrExpr = 0,
        height: IntOrExpr | None = None,
        width: IntOrExpr | None = None,
    ) -> Pipeline:
        """Extract a rectangular region.

        Args:
            top: Top offset.
            left: Left offset.
            height: Crop height (None = to end).
            width: Crop width (None = to end).
        """
        return self._append_typed(
            "crop", {"top": top, "left": left, "height": height, "width": width}
        )

    def convert_color(self, *, from_space: str, to_space: str) -> Pipeline:
        """Convert between color spaces.

        Domain: buffer → buffer

        Args:
            from_space: Source color space (rgb, bgr, hsv, lab, ycbcr, gray).
            to_space: Target color space (rgb, bgr, hsv, lab, ycbcr, gray).

        Example:
            >>> pipe = Pipeline().source("image_bytes").convert_color(from_space="rgb", to_space="hsv")
        """
        return self._append_typed(
            "cvt_color", {"from_space": from_space, "to_space": to_space}
        )

    def dilate(self, *, ksize: IntOrExpr = 3, iterations: IntOrExpr = 1) -> Pipeline:
        """Morphological dilation (local maximum over a `ksize × ksize` square). Requires single-channel input (e.g. after `.grayscale()` or `.threshold()`).

        Args:
            ksize: Size of the square structuring element. Must be odd and >= 1. Accepts
                a Polars expression for per-row dynamic values.
            iterations: Number of times the operation is applied. Accepts a Polars
                expression for per-row dynamic values.

        Example:
            >>> mask = Pipeline().source("image_bytes").grayscale().threshold(128).dilate(ksize=3)
        """
        return self._append_typed("dilate", {"ksize": ksize, "iterations": iterations})

    def equalize_histogram(self) -> Pipeline:
        """Apply histogram equalization for contrast enhancement: map each pixel
        through the normalized CDF, per channel. Output is U8.


        Example:
            >>> eq = Pipeline().source("image_bytes").grayscale().equalize_histogram()
        """
        return self._append_typed("equalize_histogram", {})

    def erode(self, *, ksize: IntOrExpr = 3, iterations: IntOrExpr = 1) -> Pipeline:
        """Morphological erosion (local minimum over a `ksize × ksize` square). Requires single-channel input (e.g. after `.grayscale()` or `.threshold()`).

        Args:
            ksize: Size of the square structuring element. Must be odd and >= 1. Accepts
                a Polars expression for per-row dynamic values.
            iterations: Number of times the operation is applied. Accepts a Polars
                expression for per-row dynamic values.

        Example:
            >>> mask = Pipeline().source("image_bytes").grayscale().threshold(128).erode(ksize=3)
        """
        return self._append_typed("erode", {"ksize": ksize, "iterations": iterations})

    def extract_contours(
        self,
        *,
        mode: str | pl.Expr = "external",
        method: str | pl.Expr = "simple",
        min_area: FloatOrExpr | None = None,
    ) -> Pipeline:
        """Extract contours from binary mask.

        The traced outline passes through the **centres** of the boundary pixels,
        so it sits half a pixel inside the region it describes: a blob filling
        ``w x h`` pixels comes back bounding ``(w-1) x (h-1)``. Rasterizing the
        result therefore erodes it by a pixel per round trip.

        Borders come back as a flat list with no hierarchy. ``mode="all"`` yields
        the exterior plus one border for each enclosed background region — holes
        that touch or nest enclose one region between them — and reassembling a
        holed contour from those is the caller's job. ``mode="external"`` keeps
        only the outermost, discarding hole borders.

        Domain transition: buffer → contour

        Args:
            mode: "external" (outer only), "tree" (full hierarchy), "all".
            method: "simple" (remove redundant), "none" (all points), "approx".
            min_area: Filter small contours. Accepts a Polars expression for per-row
                dynamic thresholds.
        """
        return self._append_typed(
            "extract_contours", {"mode": mode, "method": method, "min_area": min_area}
        )

    def extract_shape(self) -> Pipeline:
        """Extract buffer shape as a struct {height, width, channels}.

        Domain transition: buffer → vector
        """
        return self._append_typed("extract_shape", {})

    def flip(self, axes: Sequence[int]) -> Pipeline:
        """Flip along specified axes.

        Args:
            axes: Axes to flip.
        """
        return self._append_typed("flip", {"axes": axes})

    def floor(self) -> Pipeline:
        """Round toward negative infinity. Domain: buffer → buffer."""
        return self._append_typed("floor", {})

    def grayscale(self) -> Pipeline:
        """Convert to grayscale (luminance 0.299R + 0.587G + 0.114B)."""
        return self._append_typed("grayscale", {})

    def histogram(
        self,
        *,
        bins: IntOrExpr | Sequence[float] = 256,
        range: Sequence[FloatOrExpr] | None = None,
        closed: str = "left",
        output: str = "buckets",
    ) -> Pipeline:
        """Compute pixel value histogram.

        Args:
            bins: Number of bins (default 256), a Polars expression for per-row dynamic
                bin count, or an explicit list of bin edges.
            range: (min, max) tuple. Auto-detected if None.
            closed: "left" or "right" interval inclusiveness (default "left").
            output: "buckets" (list of structs), "counts" (bin counts), "normalized"
                (sum to 1.0), "quantized" (pixel indices), "edges" (bin edges).

        Example:
            >>> Pipeline().source("image_bytes").grayscale().histogram(bins=8)
        """
        return self._append_typed(
            "histogram",
            {"bins": bins, "range": range, "closed": closed, "output": output},
        )

    def invert(self) -> Pipeline:
        """Invert pixel values: `255 - pixel` for u8, `1.0 - pixel` for float [0,1]."""
        return self._append_typed("invert", {})

    def label_reduce(
        self,
        contours: pl.Expr,
        *,
        reduction: str | pl.Expr = "max",
        region_mode: str | pl.Expr = "interior",
    ) -> Pipeline:
        """Score contour regions against the current buffer values.

        This is the buffer-space variant of label reduction. It accepts contours
        via a Polars expression and returns one score per contour.

        Domain transition: buffer -> vector

        Args:
            contours: Contour-set expression (`List[Contour]`) to score.
            reduction: Reduction over contour region values (`"max"`, `"mean"`,
                `"sum"`).
            region_mode: Region selection mode. ``"interior"`` — only pixels strictly
                inside the contour polygon. ``"boundary"`` — interior pixels *plus*
                pixels on the contour boundary (avoids zero-score artifacts for sub-
                pixel contours). ``"bbox"`` — all pixels within the bounding box.
        """
        return self._append_typed(
            "label_reduce",
            {"contours": contours, "reduction": reduction, "region_mode": region_mode},
        )

    def letterbox(
        self,
        *,
        height: IntOrExpr,
        width: IntOrExpr,
        value: FloatOrExpr = 0.0,
        filter: str | pl.Expr = "lanczos3",
    ) -> Pipeline:
        """Resize image maintaining aspect ratio and pad to exact target size: fit
        within the target, then pad with centered positioning.

        Args:
            height: Target height (literal or expression).
            width: Target width (literal or expression).
            value: Fill value for padding (default 0, typically black). Accepts a Polars
                expression for per-row dynamic values.
            filter: Resampling filter for the resize step (default "lanczos3").

        Example:
            >>> pipe = Pipeline().source("image_bytes").letterbox(height=224, width=224)
        """
        return self._append_typed(
            "letterbox",
            {"height": height, "width": width, "value": value, "filter": filter},
        )

    def morphology_gradient(self, *, ksize: IntOrExpr = 3) -> Pipeline:
        """Morphological gradient (dilate - erode): an edge outline. Requires
        single-channel input.

        Args:
            ksize: Size of the square structuring element. Must be odd and >= 1. Accepts
                a Polars expression for per-row dynamic values.

        Example:
            >>> edges = Pipeline().source("image_bytes").grayscale().threshold(128).morphology_gradient(ksize=3)
        """
        return self._append_typed("morphology_gradient", {"ksize": ksize})

    def neg(self) -> Pipeline:
        """Negate every value (`-x`). Domain: buffer → buffer."""
        return self._append_typed("neg", {})

    def normalize(
        self,
        *,
        method: str = "minmax",
        mean: Sequence[FloatOrExpr] | None = None,
        std: Sequence[FloatOrExpr] | None = None,
        out_dtype: str | None = None,
    ) -> Pipeline:
        """Normalize values to a standard range.

        Args:
            method: Normalization method: "minmax" scales values to [0, 1] using per-
                element min/max; "zscore" standardizes to mean=0, std=1 using per-
                element statistics; "preset" applies ImageNet-style channel-wise
                normalization, `(x - mean[c]) / std[c]`, with the given `mean` and
                `std`.
            mean: Per-channel mean values; required for, and only valid with,
                method="preset" (e.g. ImageNet `[0.485, 0.456, 0.406]`). Each element
                may be a literal float or a Polars expression; the list length is the
                channel count.
            std: Per-channel standard deviation values; required for, and only valid
                with, method="preset" (e.g. ImageNet `[0.229, 0.224, 0.225]`). Each
                element accepts an expression, as with `mean`.
            out_dtype: Output dtype (default f32). Normalization computes in f32 and the
                result is cast to this dtype at execution. For half precision use the
                sink dtype instead (`.sink("numpy", dtype="f16")`).

        Example:
            >>> Pipeline().source().normalize(method="minmax")
            >>> Pipeline().source().normalize(
            ...     method="preset",
            ...     mean=[0.485, 0.456, 0.406],
            ...     std=[0.229, 0.224, 0.225],
            ... )
        """
        return self._append_typed(
            "normalize",
            {"method": method, "mean": mean, "std": std, "out_dtype": out_dtype},
        )

    def pad(
        self,
        *,
        top: IntOrExpr = 0,
        bottom: IntOrExpr = 0,
        left: IntOrExpr = 0,
        right: IntOrExpr = 0,
        value: FloatOrExpr = 0.0,
        mode: str | pl.Expr = "constant",
    ) -> Pipeline:
        """Add padding to the image.

        Args:
            top: Padding on top edge.
            bottom: Padding on bottom edge.
            left: Padding on left edge.
            right: Padding on right edge.
            value: Fill value for "constant" mode (default 0). Accepts a Polars
                expression for per-row dynamic values.
            mode: Padding mode - "constant", "edge", "reflect", "symmetric".

        Example:
            >>> pipe = Pipeline().source("image_bytes").pad(top=10, bottom=10)
            >>> pipe = Pipeline().source("image_bytes").pad(left=20, right=20, value=128)
        """
        return self._append_typed(
            "pad",
            {
                "top": top,
                "bottom": bottom,
                "left": left,
                "right": right,
                "value": value,
                "mode": mode,
            },
        )

    def pad_to_size(
        self,
        *,
        height: IntOrExpr,
        width: IntOrExpr,
        position: str | pl.Expr = "center",
        value: FloatOrExpr = 0.0,
    ) -> Pipeline:
        """Pad image to exact target size (computed at runtime). A larger image is
        not cropped - resize first if needed.

        Args:
            height: Target height.
            width: Target width.
            position: Where to place original content: "center" (default), "top-left" or
                "bottom-right".
            value: Fill value for padding (default 0). Accepts a Polars expression for
                per-row dynamic values.

        Example:
            >>> pipe = Pipeline().source("image_bytes").pad_to_size(height=100, width=200)
        """
        return self._append_typed(
            "pad_to_size",
            {"height": height, "width": width, "position": position, "value": value},
        )

    def perceptual_hash(
        self, *, algorithm: str = "perceptual", hash_size: int = 64
    ) -> Pipeline:
        """Compute a perceptual hash fingerprint.

        Args:
            algorithm: "perceptual" (pHash), "average" (aHash), "difference" (dHash).
            hash_size: Number of bits in the hash (must be power of 2). It fixes the
                output vector length, so it is literal-only.

        Example:
            >>> Pipeline().source("image_bytes").perceptual_hash()
        """
        return self._append_typed(
            "perceptual_hash", {"algorithm": algorithm, "hash_size": hash_size}
        )

    def _rasterize(
        self,
        size: Sequence[IntOrExpr] | LazyPipelineExpr,
        *,
        fill_value: IntOrExpr = 255,
        background: IntOrExpr = 0,
    ) -> Pipeline:
        """Rasterize contours to a mask.

        The builder is ``Pipeline.rasterize``, whose ``width``/``height`` or
        ``shape`` arguments become ``size``; it also records the shape reference's
        graph dependency and its canvas assertion.

        Domain transition: contour → buffer

        Args:
            size: ``[height, width]`` of the mask (each may be a Polars expression), or
                another node whose buffer's height and width the mask takes.
            fill_value: Inside value (default 255). Accepts a Polars expression for per-
                row dynamic values.
            background: Outside value (default 0). Accepts a Polars expression for per-
                row dynamic values.
        """
        return self._append_typed(
            "rasterize",
            {"size": size, "fill_value": fill_value, "background": background},
        )

    def reciprocal(self) -> Pipeline:
        """Reciprocal (`1 / x`; ±inf at zero). Domain: buffer → buffer."""
        return self._append_typed("reciprocal", {})

    def reduce_argmax(self, axis: int) -> Pipeline:
        """Index of the maximum value along an axis.

        Unlike other reductions it always requires an axis: a global index
        is ambiguous for a multi-dimensional array. Domain transition:
        buffer → buffer (reduced shape, i64 dtype).

        Args:
            axis: Axis along which to find the index.
        """
        return self._append_typed("reduce_argmax", {"axis": axis})

    def reduce_argmin(self, axis: int) -> Pipeline:
        """Index of the minimum value along an axis.

        Unlike other reductions it always requires an axis: a global index
        is ambiguous for a multi-dimensional array. Domain transition:
        buffer → buffer (reduced shape, i64 dtype).

        Args:
            axis: Axis along which to find the index.
        """
        return self._append_typed("reduce_argmin", {"axis": axis})

    def reduce_max(self, *, axis: int | None = None) -> Pipeline:
        """Reduce buffer by computing the maximum value.

        Domain transition: axis=None: buffer → scalar; axis=N: buffer →
        buffer (reduced shape).

        Args:
            axis: Axis to reduce along. None for global reduction. It fixes the output
                rank, so it is literal-only.
        """
        return self._append_typed("reduce_max", {"axis": axis})

    def reduce_mean(self, *, axis: int | None = None) -> Pipeline:
        """Compute arithmetic mean.

        Domain transition: axis=None: buffer → scalar; axis=N: buffer →
        buffer (reduced shape).

        Args:
            axis: Axis to reduce along. None for global reduction. It fixes the output
                rank, so it is literal-only.
        """
        return self._append_typed("reduce_mean", {"axis": axis})

    def reduce_min(self, *, axis: int | None = None) -> Pipeline:
        """Reduce buffer by computing the minimum value.

        Domain transition: axis=None: buffer → scalar; axis=N: buffer →
        buffer (reduced shape).

        Args:
            axis: Axis to reduce along. None for global reduction. It fixes the output
                rank, so it is literal-only.
        """
        return self._append_typed("reduce_min", {"axis": axis})

    def reduce_percentile(self, q: FloatOrExpr) -> Pipeline:
        """Compute the q-th percentile of all values (linear interpolation, as numpy's
        default).

        Domain transition: buffer -> scalar

        Args:
            q: Percentile to compute, in [0, 100]. Accepts a Polars expression for per-
                row dynamic values.
        """
        return self._append_typed("reduce_percentile", {"q": q})

    def reduce_popcount(self) -> Pipeline:
        """Count set bits (1s) in the buffer.

        Domain transition: buffer → scalar
        """
        return self._append_typed("reduce_popcount", {})

    def reduce_std(self, *, axis: int | None = None, ddof: IntOrExpr = 0) -> Pipeline:
        """Reduce buffer by computing the standard deviation.

        Domain transition: axis=None: buffer -> scalar; axis=N: buffer -> buffer
        (reduced shape).

        Args:
            axis: Axis to reduce along. None for global reduction.
            ddof: Delta degrees of freedom. 0 for population std (default), 1 for sample
                std. Accepts a Polars expression for per-row dynamic values.

        Example:
            >>> pipe = Pipeline().source("image_bytes").reduce_std(ddof=1)
        """
        return self._append_typed("reduce_std", {"axis": axis, "ddof": ddof})

    def reduce_sum(self) -> Pipeline:
        """Sum all elements in the buffer.

        Domain transition: buffer → scalar
        """
        return self._append_typed("reduce_sum", {})

    def relu(self) -> Pipeline:
        """Apply ReLU activation (max(0, x)): negative values become zero."""
        return self._append_typed("relu", {})

    def reshape(self, shape: Sequence[IntOrExpr]) -> Pipeline:
        """Reshape array to new dimensions.

        Args:
            shape: New shape. The number of entries fixes the output rank; each entry
                may be a Polars expression.
        """
        return self._append_typed("reshape", {"shape": shape})

    def resize(
        self, *, height: IntOrExpr, width: IntOrExpr, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image to specified dimensions.

        Args:
            height: Target height.
            width: Target width.
            filter: Interpolation: "nearest", "bilinear", "lanczos3" (default).

        Example:
            >>> Pipeline().source("image_bytes").resize(height=224, width=224)
        """
        return self._append_typed(
            "resize", {"height": height, "width": width, "filter": filter}
        )

    def resize_max(
        self, max_size: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image so the maximum dimension equals target, preserving aspect ratio (200x100 with max_size=50 gives 50x25).

        Args:
            max_size: Target for the maximum dimension (literal or expression).
            filter: Resize filter ("nearest", "bilinear", "lanczos3").

        Example:
            >>> pipe = Pipeline().source("image_bytes").resize_max(224)
        """
        return self._append_typed(
            "resize_max", {"max_size": max_size, "filter": filter}
        )

    def resize_min(
        self, min_size: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image so the minimum dimension equals target, preserving aspect ratio (200x100 with min_size=50 gives 100x50).

        Args:
            min_size: Target for the minimum dimension (literal or expression).
            filter: Resize filter ("nearest", "bilinear", "lanczos3").

        Example:
            >>> pipe = Pipeline().source("image_bytes").resize_min(224)
        """
        return self._append_typed(
            "resize_min", {"min_size": min_size, "filter": filter}
        )

    def _resize_scale(
        self,
        *,
        scale_x: FloatOrExpr,
        scale_y: FloatOrExpr,
        filter: str | pl.Expr = "lanczos3",
    ) -> Pipeline:
        """Resize image by scale factor: `new_width = input_width * scale_x`,
        `new_height = input_height * scale_y`, computed at runtime.

        The public `Pipeline.resize_scale` is sugar over this op that also accepts
        one uniform `scale`.

        Args:
            scale_x: X (width) scale factor.
            scale_y: Y (height) scale factor.
            filter: Resize filter ("nearest", "bilinear", "lanczos3").
        """
        return self._append_typed(
            "resize_scale", {"scale_x": scale_x, "scale_y": scale_y, "filter": filter}
        )

    def resize_to_height(
        self, height: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image to target height, preserving aspect ratio (width is computed at runtime).

        Args:
            height: Target height (literal or expression).
            filter: Resize filter ("nearest", "bilinear", "lanczos3").

        Example:
            >>> pipe = Pipeline().source("image_bytes").resize_to_height(224)
        """
        return self._append_typed(
            "resize_to_height", {"height": height, "filter": filter}
        )

    def resize_to_width(
        self, width: IntOrExpr, *, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image to target width, preserving aspect ratio (height is computed at runtime).

        Args:
            width: Target width (literal or expression).
            filter: Resize filter ("nearest", "bilinear", "lanczos3").

        Example:
            >>> pipe = Pipeline().source("image_bytes").resize_to_width(224)
        """
        return self._append_typed("resize_to_width", {"width": width, "filter": filter})

    def rotate(
        self,
        angle: FloatOrExpr,
        *,
        expand: bool = False,
        interpolation: str | pl.Expr = "bilinear",
        border_value: FloatOrExpr = 0.0,
    ) -> Pipeline:
        """Rotate image by specified angle.

        For angles of 90, 180, or 270 degrees, this uses zero-copy view operations
        (``interpolation`` and ``border_value`` do not apply: nothing is resampled
        and no out-of-bounds region is exposed). For arbitrary angles, the rotation
        is performed via an affine transformation using the specified
        interpolation and border value. For combined rotation + scale or explicit
        output sizing, use :meth:`rotate_and_scale` or :meth:`warp_affine`.

        Domain: buffer -> buffer

        Args:
            angle: Rotation angle in degrees (positive = clockwise). Can be a literal
                float or Polars expression.
            expand: If True, expand output dimensions to fit rotated image. If False
                (default), keep original dimensions (corners may be cropped).
            interpolation: Interpolation method for arbitrary angles -- ``"bilinear"``
                (default) or ``"nearest"``. Not applicable to 90/180/270 degree
                rotations.
            border_value: Fill value for out-of-bounds pixels (default 0). Not
                applicable to 90/180/270 degree rotations.

        Example:
            ```python
            >>> pipe = Pipeline().source("image_bytes").rotate(90)
            >>> pipe = Pipeline().source("image_bytes").rotate(45, expand=True)
            >>> pipe = Pipeline().source("image_bytes").rotate(pl.col("angle"))
            >>> pipe = Pipeline().source("image_bytes").rotate(30, interpolation="nearest")
            ```
        """
        return self._append_typed(
            "rotate",
            {
                "angle": angle,
                "expand": expand,
                "interpolation": interpolation,
                "border_value": border_value,
            },
        )

    def round(self) -> Pipeline:
        """Round to nearest, ties to even (matches Polars/numpy). Domain: buffer → buffer."""
        return self._append_typed("round", {})

    def _scale(self, factor: FloatOrExpr) -> Pipeline:
        """Multiply all values by a factor.

        The public `Pipeline.scale` is sugar over this op that adds
        `out_dtype`/`preserve_dtype` (a trailing cast).

        Args:
            factor: Scale factor.
        """
        return self._append_typed("scale", {"factor": factor})

    def sign(self) -> Pipeline:
        """Sign: `-1`/`0`/`+1` (`0` for ±0, NaN for NaN). Domain: buffer → buffer."""
        return self._append_typed("sign", {})

    def sqrt(self) -> Pipeline:
        """Square root (`sqrt(x)`; NaN for negative input). Domain: buffer → buffer."""
        return self._append_typed("sqrt", {})

    def square(self) -> Pipeline:
        """Square (`x * x`). Domain: buffer → buffer."""
        return self._append_typed("square", {})

    def subtract_constant(self, value: FloatOrExpr) -> Pipeline:
        """Subtract a constant from every value (`x - value`).

        Args:
            value: Constant subtrahend (literal or per-row expression).
        """
        return self._append_typed("subtract_constant", {"value": value})

    def threshold(self, value: FloatOrExpr) -> Pipeline:
        """Apply binary threshold: a U8 mask, 255 where the element exceeds `value`
        and 0 elsewhere (for u8 input typically 0-255; for [0, 1] floats e.g. 0.5).

        Args:
            value: Threshold value (int or float, or Polars expression).
        """
        return self._append_typed("threshold", {"value": value})

    def transpose(self, axes: Sequence[int]) -> Pipeline:
        """Transpose dimensions.

        Args:
            axes: New order of axes: a permutation of every input axis.
        """
        return self._append_typed("transpose", {"axes": axes})

    def trunc(self) -> Pipeline:
        """Round toward zero (drop the fractional part). Domain: buffer → buffer."""
        return self._append_typed("trunc", {})

    def warp_affine(
        self,
        *,
        matrix: Sequence[FloatOrExpr],
        output_size: Sequence[IntOrExpr],
        interpolation: str | pl.Expr = "bilinear",
        border_value: FloatOrExpr = 0.0,
    ) -> Pipeline:
        """Apply a 2x3 affine transformation matrix.

        The matrix ``[a, b, tx, c, d, ty]`` is a **forward** mapping from
        source to destination (same convention as OpenCV ``warpAffine``):

        ```text
        x_dst = a * x_src + b * y_src + tx
        y_dst = c * x_src + d * y_src + ty
        ```

        The kernel inverts this matrix internally for interpolation.

        Domain: buffer → buffer

        Args:
            matrix: Six-element sequence representing the 2x3 affine matrix ``[a, b, tx,
                c, d, ty]`` (forward mapping). **Each element may be a literal float or
                a Polars expression**, so a batch can apply a different (e.g. random)
                affine per row in one call — the matrix is resolved per row at
                execution.
            output_size: ``(height, width)`` of the output image. Each element accepts a
                Polars expression for per-row dynamic values.
            interpolation: Interpolation method -- ``"bilinear"`` (default) or
                ``"nearest"``.
            border_value: Pixel value for out-of-bounds regions (default 0).

        Example:
            ```python
            >>> # Translate image by (50, 30)
            >>> pipe = Pipeline().source("image_bytes").warp_affine(
            ...     matrix=[1.0, 0.0, 50.0, 0.0, 1.0, 30.0],
            ...     output_size=(224, 224),
            ... )
            >>>
            >>> # Per-sample random affine: each row uses its own matrix columns
            >>> pipe = Pipeline().source("image_bytes").warp_affine(
            ...     matrix=[pl.col("a"), pl.col("b"), pl.col("tx"),
            ...             pl.col("c"), pl.col("d"), pl.col("ty")],
            ...     output_size=(224, 224),
            ... )
            ```
        """
        return self._append_typed(
            "warp_affine",
            {
                "matrix": matrix,
                "output_size": output_size,
                "interpolation": interpolation,
                "border_value": border_value,
            },
        )


class _LazyOpsMixin:
    """The generated binary-op methods ``LazyPipelineExpr`` inherits."""

    if TYPE_CHECKING:

        def _binary_op(self, op: str, other: LazyPipelineExpr) -> LazyPipelineExpr: ...

    def add(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise addition with another array.

        For u8/u16: saturating addition (clamps to the maximum, e.g. 255 for
        u8). For f32/f64: standard addition.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.add(b).sink("numpy")
            ```
        """
        return self._binary_op("add", other)

    def bitwise_and(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise bitwise AND: for binary masks (0/255), the intersection.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.bitwise_and(b).sink("numpy")
            ```
        """
        return self._binary_op("bitwise_and", other)

    def bitwise_or(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise bitwise OR: for binary masks (0/255), the union.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.bitwise_or(b).sink("numpy")
            ```
        """
        return self._binary_op("bitwise_or", other)

    def bitwise_xor(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise bitwise XOR: for binary masks (0/255), the symmetric
        difference.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.bitwise_xor(b).sink("numpy")
            ```
        """
        return self._binary_op("bitwise_xor", other)

    def blend(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Normalized blend (element-wise), for image blending/compositing.

        For u8: (a/255) * (b/255) * 255. For u16: (a/65535) * (b/65535) *
        65535. For f32/f64: standard multiplication.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.blend(b).sink("numpy")
            ```
        """
        return self._binary_op("blend", other)

    def divide(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise division.

        For u8/u16: integer division, with division by zero yielding 0. For
        f32/f64: standard division.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.divide(b).sink("numpy")
            ```
        """
        return self._binary_op("divide", other)

    def maximum(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise maximum of two arrays, for compositing, clamping and
        non-linear image processing.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.maximum(b).sink("numpy")
            ```
        """
        return self._binary_op("maximum", other)

    def minimum(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise minimum of two arrays, for compositing, clamping and
        non-linear image processing.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.minimum(b).sink("numpy")
            ```
        """
        return self._binary_op("minimum", other)

    def multiply(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise multiplication.

        For u8/u16: saturating multiplication (clamps to the maximum). For
        f32/f64: standard multiplication. For normalized image blending
        (values treated as [0, 1]), use ``blend`` instead.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.multiply(b).sink("numpy")
            ```
        """
        return self._binary_op("multiply", other)

    def ratio(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Scaled ratio: a/b scaled to the full range of the dtype.

        For u8: (a/b) * 255, clamped to [0, 255]. For u16: (a/b) * 65535,
        clamped to [0, 65535]. For f32/f64: standard division.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.ratio(b).sink("numpy")
            ```
        """
        return self._binary_op("ratio", other)

    def subtract(self, other: LazyPipelineExpr) -> LazyPipelineExpr:
        """Element-wise subtraction.

        For u8/u16: saturating subtraction (clamps to 0). For f32/f64:
        standard subtraction.

        Args:
            other: The expression to combine with, element-wise.

        Example:
            ```python
            >>> a = pl.col("image1").cv.pipe(pipe1)
            >>> b = pl.col("image2").cv.pipe(pipe2)
            >>> result = a.subtract(b).sink("numpy")
            ```
        """
        return self._binary_op("subtract", other)
