# This file is generated by scripts/gen_ops.py from tests/golden/op_catalog.json.
# Do not edit by hand: change the op's Rust definition in src/ops/, re-bless the
# catalogue (POLARS_CV_BLESS=1 cargo test -p polars-cv catalog_matches), then
# rerun the generator.
"""Builder methods generated from the typed op catalogue."""

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import polars as pl

    from polars_cv._types import FloatOrExpr, IntOrExpr
    from polars_cv.pipeline import Pipeline

#: Ops whose wire form is typed (bare values and slots).
TYPED_OPS: frozenset[str] = frozenset(
    [
        "abs",
        "add_constant",
        "adjust_contrast",
        "adjust_gamma",
        "cast",
        "ceil",
        "clamp",
        "clamp_max",
        "clamp_min",
        "crop",
        "flip",
        "floor",
        "histogram",
        "invert",
        "neg",
        "normalize",
        "reciprocal",
        "relu",
        "reshape",
        "resize",
        "round",
        "scale",
        "sign",
        "sqrt",
        "square",
        "subtract_constant",
        "transpose",
        "trunc",
        "warp_affine",
    ]
)

#: Each typed op's field types, as the catalogue describes them.
OP_FIELDS: dict[str, dict[str, Any]] = {
    "abs": {},
    "add_constant": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "adjust_contrast": {"factor": {"kind": "scalar", "per_row": True, "py": "float"}},
    "adjust_gamma": {"gamma": {"kind": "scalar", "per_row": True, "py": "float"}},
    "cast": {
        "dtype": {
            "kind": "scalar",
            "per_row": False,
            "py": "DType",
            "variants": [
                "u8",
                "i8",
                "u16",
                "i16",
                "u32",
                "i32",
                "u64",
                "i64",
                "f32",
                "f64",
            ],
        }
    },
    "ceil": {},
    "clamp": {
        "min": {"kind": "scalar", "per_row": True, "py": "float"},
        "max": {"kind": "scalar", "per_row": True, "py": "float"},
    },
    "clamp_max": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "clamp_min": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "crop": {
        "top": {"kind": "scalar", "per_row": True, "py": "int"},
        "left": {"kind": "scalar", "per_row": True, "py": "int"},
        "height": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
        "width": {
            "kind": "optional",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
    },
    "flip": {
        "axes": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "floor": {},
    "histogram": {
        "bins": {
            "kind": "one_of",
            "options": [
                {"kind": "scalar", "per_row": True, "py": "int"},
                {
                    "kind": "list",
                    "inner": {"kind": "scalar", "per_row": False, "py": "float"},
                },
            ],
        },
        "range": {
            "kind": "optional",
            "inner": {
                "kind": "array",
                "len": 2,
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "closed": {
            "kind": "scalar",
            "per_row": False,
            "py": "HistogramClosed",
            "variants": ["left", "right"],
        },
        "output": {
            "kind": "scalar",
            "per_row": False,
            "py": "HistogramOutput",
            "variants": ["counts", "normalized", "quantized", "edges", "buckets"],
        },
    },
    "invert": {},
    "neg": {},
    "normalize": {
        "method": {
            "kind": "scalar",
            "per_row": False,
            "py": "NormalizeMethod",
            "variants": ["minmax", "zscore", "preset"],
        },
        "mean": {
            "kind": "optional",
            "inner": {
                "kind": "list",
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "std": {
            "kind": "optional",
            "inner": {
                "kind": "list",
                "inner": {"kind": "scalar", "per_row": True, "py": "float"},
            },
        },
        "out_dtype": {
            "kind": "optional",
            "inner": {
                "kind": "scalar",
                "per_row": False,
                "py": "DType",
                "variants": [
                    "u8",
                    "i8",
                    "u16",
                    "i16",
                    "u32",
                    "i32",
                    "u64",
                    "i64",
                    "f32",
                    "f64",
                ],
            },
        },
    },
    "reciprocal": {},
    "relu": {},
    "reshape": {
        "shape": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        }
    },
    "resize": {
        "height": {"kind": "scalar", "per_row": True, "py": "int"},
        "width": {"kind": "scalar", "per_row": True, "py": "int"},
        "filter": {
            "kind": "scalar",
            "per_row": True,
            "py": "FilterType",
            "variants": ["nearest", "bilinear", "catmullrom", "gaussian", "lanczos3"],
        },
    },
    "round": {},
    "scale": {"factor": {"kind": "scalar", "per_row": True, "py": "float"}},
    "sign": {},
    "sqrt": {},
    "square": {},
    "subtract_constant": {"value": {"kind": "scalar", "per_row": True, "py": "float"}},
    "transpose": {
        "axes": {
            "kind": "list",
            "inner": {"kind": "scalar", "per_row": False, "py": "int"},
        }
    },
    "trunc": {},
    "warp_affine": {
        "matrix": {
            "kind": "array",
            "len": 6,
            "inner": {"kind": "scalar", "per_row": True, "py": "float"},
        },
        "output_size": {
            "kind": "array",
            "len": 2,
            "inner": {"kind": "scalar", "per_row": True, "py": "int"},
        },
        "interpolation": {
            "kind": "scalar",
            "per_row": True,
            "py": "InterpolationType",
            "variants": ["nearest", "bilinear"],
        },
        "border_value": {"kind": "scalar", "per_row": True, "py": "float"},
    },
}


class _OpsMixin:
    """The generated builder methods ``Pipeline`` inherits."""

    if TYPE_CHECKING:

        def _append_typed(self, op_name: str, values: dict[str, Any]) -> Pipeline: ...

    def abs(self) -> Pipeline:
        """Absolute value (`|x|`). Domain: buffer → buffer."""
        return self._append_typed("abs", {})

    def add_constant(self, value: FloatOrExpr) -> Pipeline:
        """Add a constant to every value (`x + value`).

        Args:
            value: Constant addend (literal or per-row expression).
        """
        return self._append_typed("add_constant", {"value": value})

    def adjust_contrast(self, *, factor: FloatOrExpr) -> Pipeline:
        """Adjust image contrast: `(pixel - mean) * factor + mean`.

        Args:
            factor: Contrast factor. 1.0 = no change, >1 = more contrast, <1 = less.

        Example:
            >>> pipe = Pipeline().source("image_bytes").adjust_contrast(factor=1.5)
        """
        return self._append_typed("adjust_contrast", {"factor": factor})

    def adjust_gamma(self, *, gamma: FloatOrExpr) -> Pipeline:
        """Apply gamma (power-law) correction: normalize to [0,1], raise to `gamma`,
        denormalize.

        Args:
            gamma: Gamma value. <1 = brighter, >1 = darker, 1.0 = no change.

        Example:
            >>> pipe = Pipeline().source("image_bytes").adjust_gamma(gamma=0.5)
        """
        return self._append_typed("adjust_gamma", {"gamma": gamma})

    def cast(self, dtype: str) -> Pipeline:
        """Cast to a different data type.

        Args:
            dtype: Target data type (e.g., "f32", "u8").
        """
        return self._append_typed("cast", {"dtype": dtype})

    def ceil(self) -> Pipeline:
        """Round toward positive infinity. Domain: buffer → buffer."""
        return self._append_typed("ceil", {})

    def _clamp(self, min: FloatOrExpr, max: FloatOrExpr) -> Pipeline:
        """Clamp values to a range.

        The public `Pipeline.clamp` is sugar over this op that adds
        `out_dtype`/`preserve_dtype` (a trailing cast).

        Args:
            min: Minimum value (literal or expression).
            max: Maximum value (literal or expression).
        """
        return self._append_typed("clamp", {"min": min, "max": max})

    def clamp_max(self, value: FloatOrExpr) -> Pipeline:
        """Cap values at `value` (`min(x, value)`); one-sided clamp.

        Args:
            value: Upper bound (literal or per-row expression).
        """
        return self._append_typed("clamp_max", {"value": value})

    def clamp_min(self, value: FloatOrExpr) -> Pipeline:
        """Floor values at `value` (`max(x, value)`); one-sided clamp.

        Args:
            value: Lower bound (literal or per-row expression).
        """
        return self._append_typed("clamp_min", {"value": value})

    def crop(
        self,
        *,
        top: IntOrExpr = 0,
        left: IntOrExpr = 0,
        height: IntOrExpr | None = None,
        width: IntOrExpr | None = None,
    ) -> Pipeline:
        """Extract a rectangular region.

        Args:
            top: Top offset.
            left: Left offset.
            height: Crop height (None = to end).
            width: Crop width (None = to end).
        """
        return self._append_typed(
            "crop", {"top": top, "left": left, "height": height, "width": width}
        )

    def flip(self, axes: Sequence[int]) -> Pipeline:
        """Flip along specified axes.

        Args:
            axes: Axes to flip.
        """
        return self._append_typed("flip", {"axes": axes})

    def floor(self) -> Pipeline:
        """Round toward negative infinity. Domain: buffer → buffer."""
        return self._append_typed("floor", {})

    def histogram(
        self,
        bins: IntOrExpr | Sequence[float] = 256,
        range: Sequence[FloatOrExpr] | None = None,
        closed: str = "left",
        output: str = "buckets",
    ) -> Pipeline:
        """Compute pixel value histogram.

        Args:
            bins: Number of bins (default 256), a Polars expression for per-row dynamic
                bin count, or an explicit list of bin edges.
            range: (min, max) tuple. Auto-detected if None.
            closed: "left" or "right" interval inclusiveness (default "left").
            output: "buckets" (list of structs), "counts" (bin counts), "normalized"
                (sum to 1.0), "quantized" (pixel indices), "edges" (bin edges).

        Example:
            >>> Pipeline().source("image_bytes").grayscale().histogram(bins=8)
        """
        return self._append_typed(
            "histogram",
            {"bins": bins, "range": range, "closed": closed, "output": output},
        )

    def invert(self) -> Pipeline:
        """Invert pixel values: `255 - pixel` for u8, `1.0 - pixel` for float [0,1]."""
        return self._append_typed("invert", {})

    def neg(self) -> Pipeline:
        """Negate every value (`-x`). Domain: buffer → buffer."""
        return self._append_typed("neg", {})

    def normalize(
        self,
        method: str = "minmax",
        mean: Sequence[FloatOrExpr] | None = None,
        std: Sequence[FloatOrExpr] | None = None,
        out_dtype: str | None = None,
    ) -> Pipeline:
        """Normalize values to a standard range.

        Args:
            method: Normalization method: "minmax" scales values to [0, 1] using per-
                element min/max; "zscore" standardizes to mean=0, std=1 using per-
                element statistics; "preset" applies ImageNet-style channel-wise
                normalization, `(x - mean[c]) / std[c]`, with the given `mean` and
                `std`.
            mean: Per-channel mean values; required for, and only valid with,
                method="preset" (e.g. ImageNet `[0.485, 0.456, 0.406]`). Each element
                may be a literal float or a Polars expression; the list length is the
                channel count.
            std: Per-channel standard deviation values; required for, and only valid
                with, method="preset" (e.g. ImageNet `[0.229, 0.224, 0.225]`). Each
                element accepts an expression, as with `mean`.
            out_dtype: Output dtype (default f32). Normalization computes in f32 and the
                result is cast to this dtype at execution. For half precision use the
                sink dtype instead (`.sink("numpy", dtype="f16")`).

        Example:
            >>> Pipeline().source().normalize(method="minmax")
            >>> Pipeline().source().normalize(
            ...     method="preset",
            ...     mean=[0.485, 0.456, 0.406],
            ...     std=[0.229, 0.224, 0.225],
            ... )
        """
        return self._append_typed(
            "normalize",
            {"method": method, "mean": mean, "std": std, "out_dtype": out_dtype},
        )

    def reciprocal(self) -> Pipeline:
        """Reciprocal (`1 / x`; ±inf at zero). Domain: buffer → buffer."""
        return self._append_typed("reciprocal", {})

    def relu(self) -> Pipeline:
        """Apply ReLU activation (max(0, x)): negative values become zero."""
        return self._append_typed("relu", {})

    def reshape(self, shape: Sequence[IntOrExpr]) -> Pipeline:
        """Reshape array to new dimensions.

        Args:
            shape: New shape. The number of entries fixes the output rank; each entry
                may be a Polars expression.
        """
        return self._append_typed("reshape", {"shape": shape})

    def resize(
        self, *, height: IntOrExpr, width: IntOrExpr, filter: str | pl.Expr = "lanczos3"
    ) -> Pipeline:
        """Resize image to specified dimensions.

        Args:
            height: Target height.
            width: Target width.
            filter: Interpolation: "nearest", "bilinear", "lanczos3" (default).

        Example:
            >>> Pipeline().source("image_bytes").resize(height=224, width=224)
        """
        return self._append_typed(
            "resize", {"height": height, "width": width, "filter": filter}
        )

    def round(self) -> Pipeline:
        """Round to nearest, ties to even (matches Polars/numpy). Domain: buffer → buffer."""
        return self._append_typed("round", {})

    def _scale(self, factor: FloatOrExpr) -> Pipeline:
        """Multiply all values by a factor.

        The public `Pipeline.scale` is sugar over this op that adds
        `out_dtype`/`preserve_dtype` (a trailing cast).

        Args:
            factor: Scale factor.
        """
        return self._append_typed("scale", {"factor": factor})

    def sign(self) -> Pipeline:
        """Sign: `-1`/`0`/`+1` (`0` for ±0, NaN for NaN). Domain: buffer → buffer."""
        return self._append_typed("sign", {})

    def sqrt(self) -> Pipeline:
        """Square root (`sqrt(x)`; NaN for negative input). Domain: buffer → buffer."""
        return self._append_typed("sqrt", {})

    def square(self) -> Pipeline:
        """Square (`x * x`). Domain: buffer → buffer."""
        return self._append_typed("square", {})

    def subtract_constant(self, value: FloatOrExpr) -> Pipeline:
        """Subtract a constant from every value (`x - value`).

        Args:
            value: Constant subtrahend (literal or per-row expression).
        """
        return self._append_typed("subtract_constant", {"value": value})

    def transpose(self, axes: Sequence[int]) -> Pipeline:
        """Transpose dimensions.

        Args:
            axes: New order of axes: a permutation of every input axis.
        """
        return self._append_typed("transpose", {"axes": axes})

    def trunc(self) -> Pipeline:
        """Round toward zero (drop the fractional part). Domain: buffer → buffer."""
        return self._append_typed("trunc", {})

    def warp_affine(
        self,
        matrix: Sequence[FloatOrExpr],
        output_size: Sequence[IntOrExpr],
        *,
        interpolation: str | pl.Expr = "bilinear",
        border_value: FloatOrExpr = 0.0,
    ) -> Pipeline:
        """Apply a 2x3 affine transformation matrix.

        The matrix ``[a, b, tx, c, d, ty]`` is a **forward** mapping from
        source to destination (same convention as OpenCV ``warpAffine``)::

            x_dst = a * x_src + b * y_src + tx
            y_dst = c * x_src + d * y_src + ty

        The kernel inverts this matrix internally for interpolation.

        Domain: buffer → buffer

        Args:
            matrix: Six-element sequence representing the 2x3 affine matrix ``[a, b, tx,
                c, d, ty]`` (forward mapping). **Each element may be a literal float or
                a Polars expression**, so a batch can apply a different (e.g. random)
                affine per row in one call — the matrix is resolved per row at
                execution.
            output_size: ``(height, width)`` of the output image. Each element accepts a
                Polars expression for per-row dynamic values.
            interpolation: Interpolation method -- ``"bilinear"`` (default) or
                ``"nearest"``.
            border_value: Pixel value for out-of-bounds regions (default 0).

        Example:
            ```python
            >>> # Translate image by (50, 30)
            >>> pipe = Pipeline().source("image_bytes").warp_affine(
            ...     matrix=[1.0, 0.0, 50.0, 0.0, 1.0, 30.0],
            ...     output_size=(224, 224),
            ... )
            >>>
            >>> # Per-sample random affine: each row uses its own matrix columns
            >>> pipe = Pipeline().source("image_bytes").warp_affine(
            ...     matrix=[pl.col("a"), pl.col("b"), pl.col("tx"),
            ...             pl.col("c"), pl.col("d"), pl.col("ty")],
            ...     output_size=(224, 224),
            ... )
            ```
        """
        return self._append_typed(
            "warp_affine",
            {
                "matrix": matrix,
                "output_size": output_size,
                "interpolation": interpolation,
                "border_value": border_value,
            },
        )
