"""Lazy, streaming bootstrap resampler + vectorized ``bootstrap_ci``.

The resample frame is generated by a position-independent hash expression
(:func:`polars_cv.metrics._bootstrap._lazy_resample`) rather than a Python loop
over eager ``pl.Series.sample`` calls, so the whole bootstrap runs as one
streaming plan. These tests pin the properties that buys us:

* the generator stays a ``LazyFrame`` (nothing materialises the
  ``n_bootstrap * n_units`` frame in Python),
* a fixed seed is reproducible *and* invariant to the runtime thread count
  (the old join-order path silently varied across platforms — see the macOS
  negative-AUC comment in ``_bootstrap.py``),
* stratified draws keep each stratum's size,
* ``MetricResult.bootstrap_ci`` is the vectorized single authority — its
  ``auc`` distribution is bit-identical to ``bootstrap_pr_auc``.
"""

from __future__ import annotations

import subprocess
import sys
import textwrap

import polars as pl
import pytest

from polars_cv.metrics import DetectionTable, average_precision, precision_recall_curve
from polars_cv.metrics._bootstrap import (
    _lazy_resample,
    bootstrap_pr_auc,
)
from polars_cv.metrics._types import (
    COL_CLASS_ID,
    COL_DET_IDX,
    COL_GT_IDX,
    COL_GT_LABEL,
    COL_IMAGE_ID,
    COL_IOU,
    COL_IS_TP,
    COL_N_GTS,
    COL_SCORE,
    COL_WEIGHT,
    DEFAULT_CLASS,
)


def _table() -> DetectionTable:
    det = pl.DataFrame(
        {
            COL_IMAGE_ID: ["a", "a", "b", "b", "c", "d", "e", "f"],
            COL_CLASS_ID: [DEFAULT_CLASS] * 8,
            COL_SCORE: [0.95, 0.6, 0.8, 0.4, 0.7, 0.55, 0.3, 0.9],
            COL_IS_TP: [True, False, True, True, False, True, False, True],
            COL_GT_IDX: [0, None, 0, 1, None, 0, None, 0],
            COL_IOU: [0.9, 0.0, 0.85, 0.7, 0.0, 0.8, 0.0, 0.95],
            COL_DET_IDX: [0, 1, 0, 1, 0, 0, 0, 0],
        },
        schema={
            COL_IMAGE_ID: pl.String,
            COL_CLASS_ID: pl.String,
            COL_SCORE: pl.Float64,
            COL_IS_TP: pl.Boolean,
            COL_GT_IDX: pl.UInt32,
            COL_IOU: pl.Float64,
            COL_DET_IDX: pl.UInt32,
        },
    )
    meta = pl.DataFrame(
        {
            COL_IMAGE_ID: ["a", "b", "c", "d", "e", "f"],
            COL_CLASS_ID: [DEFAULT_CLASS] * 6,
            COL_N_GTS: [1, 2, 0, 1, 0, 1],
            COL_WEIGHT: [1.0] * 6,
            COL_GT_LABEL: [True, True, False, True, False, True],
        }
    )
    return DetectionTable.from_matched(det, meta)


class TestLazySampler:
    def test_returns_lazyframe(self) -> None:
        base = pl.LazyFrame({COL_IMAGE_ID: ["a", "b", "c"]})
        out = _lazy_resample(
            base, unit_col=COL_IMAGE_ID, n_bootstrap=10, confidence=0.95, seed=1
        )
        assert isinstance(out, pl.LazyFrame)
        df = out.collect(engine="streaming")
        assert df.height == 30  # n_bootstrap * n_units
        assert set(df.columns) == {"bootstrap_id", COL_IMAGE_ID, "_slot"}

    def test_same_seed_reproducible(self) -> None:
        # Draw *values* are deterministic for a fixed seed; the row order the
        # streaming joins emit is not (and need not be — downstream keys off
        # ``_slot`` and order-independent group-bys), so compare sorted content.
        base = pl.LazyFrame({COL_IMAGE_ID: [f"i{k}" for k in range(6)]})
        by = ["bootstrap_id", "_slot", COL_IMAGE_ID]
        a = (
            _lazy_resample(
                base, unit_col=COL_IMAGE_ID, n_bootstrap=50, confidence=0.95, seed=3
            )
            .collect(engine="streaming")
            .sort(by)
        )
        b = (
            _lazy_resample(
                base, unit_col=COL_IMAGE_ID, n_bootstrap=50, confidence=0.95, seed=3
            )
            .collect(engine="streaming")
            .sort(by)
        )
        assert a.equals(b)

    def test_stratified_preserves_stratum_sizes(self) -> None:
        base = pl.LazyFrame(
            {
                COL_IMAGE_ID: ["a", "b", "c", "d", "e", "f"],
                COL_GT_LABEL: [True, True, False, True, False, True],
            }
        )
        out = _lazy_resample(
            base,
            unit_col=COL_IMAGE_ID,
            n_bootstrap=40,
            confidence=0.95,
            seed=5,
            strata_col=COL_GT_LABEL,
        ).collect(engine="streaming")
        labelled = out.join(base.collect(), on=COL_IMAGE_ID, how="left")
        per = labelled.group_by("bootstrap_id", COL_GT_LABEL).len()
        # True stratum has 4 members, False has 2: every replicate must redraw
        # exactly that many of each.
        sizes = {
            row[COL_GT_LABEL]: row["len"]
            for row in per.group_by(COL_GT_LABEL)
            .agg(pl.col("len").unique())
            .iter_rows(named=True)
        }
        assert sizes[True] == [4]
        assert sizes[False] == [2]

    def test_invalid_params_raise(self) -> None:
        base = pl.LazyFrame({COL_IMAGE_ID: ["a"]})
        with pytest.raises(ValueError, match="n_bootstrap"):
            _lazy_resample(
                base, unit_col=COL_IMAGE_ID, n_bootstrap=0, confidence=0.95, seed=1
            ).collect()
        with pytest.raises(ValueError, match="confidence"):
            _lazy_resample(
                base, unit_col=COL_IMAGE_ID, n_bootstrap=10, confidence=1.5, seed=1
            ).collect()
        with pytest.raises(ValueError, match="empty"):
            _lazy_resample(
                pl.LazyFrame({COL_IMAGE_ID: []}, schema={COL_IMAGE_ID: pl.String}),
                unit_col=COL_IMAGE_ID,
                n_bootstrap=10,
                confidence=0.95,
                seed=1,
            ).collect()


class TestThreadCountInvariant:
    """A fixed seed gives an identical CI regardless of ``POLARS_MAX_THREADS``.

    The draw is a hash of each row's own global slot index, so it does not
    depend on how the streaming engine splits work — the property the old
    join-order path could not guarantee. Run in subprocesses because Polars
    reads the thread count once at import.
    """

    _SNIPPET = textwrap.dedent(
        """
        import polars as pl
        from polars_cv.metrics import DetectionTable
        from polars_cv.metrics._bootstrap import bootstrap_froc_auc
        from polars_cv.metrics._types import (
            COL_CLASS_ID, COL_DET_IDX, COL_GT_IDX, COL_GT_LABEL, COL_IMAGE_ID,
            COL_IOU, COL_IS_TP, COL_N_GTS, COL_SCORE, COL_WEIGHT,
        )
        imgs = [("a",0.9,True),("b",0.8,True),("c",0.7,False),
                ("d",0.6,True),("e",0.5,False),("f",0.4,True)]
        det = pl.DataFrame(
            {COL_IMAGE_ID:[i for i,_,_ in imgs], COL_CLASS_ID:["__all__"]*6,
             COL_SCORE:[s for _,s,_ in imgs], COL_IS_TP:[t for _,_,t in imgs],
             COL_GT_IDX:[0 if t else None for _,_,t in imgs],
             COL_IOU:[0.7 if t else 0.0 for _,_,t in imgs], COL_DET_IDX:list(range(6))},
            schema={COL_IMAGE_ID:pl.String, COL_CLASS_ID:pl.String, COL_SCORE:pl.Float64,
                    COL_IS_TP:pl.Boolean, COL_GT_IDX:pl.UInt32, COL_IOU:pl.Float64,
                    COL_DET_IDX:pl.UInt32})
        meta = pl.DataFrame(
            {COL_IMAGE_ID:[i for i,_,_ in imgs], COL_CLASS_ID:["__all__"]*6,
             COL_N_GTS:[1 if t else 0 for _,_,t in imgs], COL_WEIGHT:[1.0]*6,
             COL_GT_LABEL:[t for _,_,t in imgs]},
            schema={COL_IMAGE_ID:pl.String, COL_CLASS_ID:pl.String, COL_N_GTS:pl.Int64,
                    COL_WEIGHT:pl.Float64, COL_GT_LABEL:pl.Boolean})
        t = DetectionTable.from_matched(det, meta, matching_iou_threshold=0.5)
        r = bootstrap_froc_auc(t, n_bootstrap=200, seed=123)
        print(repr(r.distribution))
        """
    )

    def _run(self, threads: int) -> str:
        import os

        env = dict(os.environ, POLARS_MAX_THREADS=str(threads))
        out = subprocess.run(
            [sys.executable, "-c", self._SNIPPET],
            capture_output=True,
            text=True,
            env=env,
            check=True,
        )
        return out.stdout.strip()

    def test_distribution_matches_across_thread_counts(self) -> None:
        assert self._run(1) == self._run(4)


class TestVectorizedBootstrapCi:
    """``MetricResult.bootstrap_ci`` runs as one grouped plan, no Python loop."""

    def test_auc_matches_bootstrap_pr_auc(self) -> None:
        table = _table()
        pr = precision_recall_curve(table)
        ci = pr.bootstrap_ci(n_bootstrap=100, seed=42, metric="auc")
        direct = bootstrap_pr_auc(table, n_bootstrap=100, seed=42)
        # Same stratified resample + same all-points estimator -> identical.
        assert ci.distribution == direct.distribution
        assert ci.point_estimate == pytest.approx(average_precision(table))

    def test_threshold_metrics_bracket_point(self) -> None:
        pr = precision_recall_curve(_table())
        for metric in ("precision_at", "recall_at"):
            ci = pr.bootstrap_ci(
                n_bootstrap=100, seed=1, metric=metric, metric_kwargs={"threshold": 0.5}
            )
            assert len(ci.distribution) == 100
            assert ci.ci_lower <= ci.point_estimate <= ci.ci_upper

    def test_multi_metric_shares_resample(self) -> None:
        pr = precision_recall_curve(_table())
        multi = pr.bootstrap_ci(
            n_bootstrap=50,
            seed=7,
            metric={
                "ap": {"metric": "auc"},
                "p50": {"metric": "precision_at", "threshold": 0.5},
            },
        )
        assert set(multi) == {"ap", "p50"}
        # ap here equals the single-metric auc run on the same seed.
        single = pr.bootstrap_ci(n_bootstrap=50, seed=7, metric="auc")
        assert multi["ap"].distribution == single.distribution

    def test_reproducible(self) -> None:
        pr = precision_recall_curve(_table())
        r1 = pr.bootstrap_ci(n_bootstrap=120, seed=9, metric="auc")
        r2 = pr.bootstrap_ci(n_bootstrap=120, seed=9, metric="auc")
        assert r1.distribution == r2.distribution

    def test_unsupported_metric_raises(self) -> None:
        pr = precision_recall_curve(_table())
        with pytest.raises(ValueError, match="no vectorized bootstrap form"):
            pr.bootstrap_ci(n_bootstrap=10, seed=1, metric="recall_at_iou")

    def test_unsupported_auc_method_raises(self) -> None:
        pr = precision_recall_curve(_table())
        with pytest.raises(ValueError, match="all_points"):
            pr.bootstrap_ci(
                n_bootstrap=10,
                seed=1,
                metric="auc",
                metric_kwargs={"method": "11_point"},
            )
