#!/usr/bin/env python
"""Generate ``python/polars_cv/_ops_generated.py`` from the typed op catalogue.

The catalogue (``tests/golden/op_catalog.json``) is emitted by the Rust op
definitions in ``src/ops/`` and pinned there by the Rust test
``catalog_matches_the_committed_file``; this script reads that file, never the
compiled extension, so it runs without a build. It writes:

- ``TYPED_OPS``: the op names that cross the wire in the typed form;
- ``OP_FIELDS``: each typed op's field types, which the builder's one encoder
  (``Pipeline._append_typed``) reads;
- ``_OpsMixin``: one builder method per op (``_``-prefixed for an internal op
  that hand-written sugar wraps), with the signature, defaults
  and docstring the Rust definition declares. ``Pipeline`` inherits it. A
  ``lazy_only`` op (one combining this expression with other graph nodes) has
  no ``Pipeline`` method: its builder is ``LazyPipelineExpr``'s, which owns the
  graph wiring, and ``test_every_lazy_only_op_is_a_lazy_method_with_its_fields``
  pins that method to the op's fields.

Usage::

    python scripts/gen_ops.py            # (re)write the module
    python scripts/gen_ops.py --check    # exit 1 if it is stale
"""

from __future__ import annotations

import json
import re
import sys
import textwrap
from pathlib import Path
from typing import Any

_PKG = Path(__file__).resolve().parents[1]
CATALOG = _PKG / "tests" / "golden" / "op_catalog.json"
OUTPUT = _PKG / "python" / "polars_cv" / "_ops_generated.py"

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from _format import ruff_format  # noqa: E402

_HEADER = '''\
# This file is generated by scripts/gen_ops.py from tests/golden/op_catalog.json.
# Do not edit by hand: change the op's Rust definition in src/ops/, re-bless the
# catalogue (POLARS_CV_BLESS=1 cargo test -p polars-cv catalog_matches), then
# rerun the generator.
"""Builder methods generated from the typed op catalogue."""

from __future__ import annotations

{imports}
'''

#: Python annotation per catalogue scalar type, (per-row, literal).
_SCALAR = {
    "int": ("IntOrExpr", "int"),
    "float": ("FloatOrExpr", "float"),
    "bool": ("BoolOrExpr", "bool"),
}

#: Docstring width, less the method body's eight-space indent.
_DOC_WIDTH = 88 - 8

#: Docstring section headers the generated ``Args:`` block goes before.
_SECTION = re.compile(r"^(Example|Examples|Returns|Raises|Note|Notes|Warning):\s*$")


def annotation(ty: dict[str, Any]) -> str:
    """The Python annotation for a catalogue field type."""
    kind = ty["kind"]
    if kind == "scalar":
        if ty.get("variants"):
            return "str | pl.Expr" if ty["per_row"] else "str"
        per_row, literal = _SCALAR[ty["py"]]
        return per_row if ty["per_row"] else literal
    if kind == "optional":
        return f"{annotation(ty['inner'])} | None"
    if kind in ("array", "list"):
        return f"Sequence[{annotation(ty['inner'])}]"
    if kind == "one_of":
        return " | ".join(annotation(option) for option in ty["options"])
    msg = f"unknown catalogue type kind {kind!r}"
    raise ValueError(msg)


def _default(field: dict[str, Any]) -> str | None:
    if "default" in field:
        return repr(field["default"])
    if field["type"]["kind"] == "optional":
        return "None"
    return None


def _indent(text: str, prefix: str) -> str:
    return "\n".join(prefix + line if line.strip() else "" for line in text.split("\n"))


def docstring(op: dict[str, Any]) -> str:
    """The op doc with a Google ``Args:`` block from the field docs."""
    lines = op["doc"].split("\n")
    at = next((i for i, line in enumerate(lines) if _SECTION.match(line)), len(lines))
    args = []
    for field in op["fields"]:
        # Rewrapped: the Rust doc comment's line breaks sit at a different
        # indent, and the rendered line must fit the formatter's limit.
        args += textwrap.wrap(
            " ".join(field["doc"].split()),
            width=_DOC_WIDTH,
            initial_indent=f"    {field['name']}: ",
            subsequent_indent="        ",
        )
    block = ["Args:", *args] if args else []
    body = lines[:at]
    while body and not body[-1].strip():
        body.pop()
    tail = lines[at:]
    parts = [*body, "", *block]
    if tail:
        parts += ["", *tail]
    return "\n".join(parts).rstrip()


def method_name(op: dict[str, Any]) -> str:
    """The generated method's name.

    A ``public`` op is the Python method itself. An ``internal`` one is the
    building block a hand-written sugar method on ``Pipeline`` calls (``scale``
    adds ``out_dtype``/``preserve_dtype`` over ``_scale``), so it is private.
    """
    if op["visibility"] == "public":
        return op["python"]
    if op["visibility"] == "internal":
        return f"_{op['python']}"
    msg = f"gen_ops.py cannot yet place {op['visibility']} op {op['name']!r}"
    raise ValueError(msg)


def method(op: dict[str, Any]) -> str:
    """Render one builder method."""
    params = ["self"]
    keyword_only = False
    for field in op["fields"]:
        if not field["positional"] and not keyword_only:
            params.append("*")
            keyword_only = True
        text = f"{field['name']}: {annotation(field['type'])}"
        default = _default(field)
        if default is not None:
            text += f" = {default}"
        params.append(text)
    values = ", ".join(f'"{f["name"]}": {f["name"]}' for f in op["fields"])
    doc = _indent(docstring(op), "        ").lstrip()
    return (
        f"    def {method_name(op)}({', '.join(params)}) -> Pipeline:\n"
        f'        """{doc}\n        """\n'
        f'        return self._append_typed("{op["name"]}", {{{values}}})\n'
    )


def _imports(methods: str) -> str:
    """The import block: only what the rendered methods name (ruff F401)."""
    aliases = sorted(
        name
        for name in ("BoolOrExpr", "FloatOrExpr", "IntOrExpr")
        if re.search(rf"\b{name}\b", methods)
    )
    lines = []
    if "Sequence[" in methods:
        lines.append("from collections.abc import Sequence")
    lines.append("from typing import TYPE_CHECKING, Any\n\nif TYPE_CHECKING:")
    if "pl.Expr" in methods:
        lines.append("    import polars as pl\n")
    if aliases:
        lines.append(f"    from polars_cv._types import {', '.join(aliases)}")
    lines.append("    from polars_cv.pipeline import Pipeline")
    return "\n".join(lines)


def render(catalog: list[dict[str, Any]]) -> str:
    """The whole generated module, formatted."""
    names = sorted(op["name"] for op in catalog)
    fields = {
        op["name"]: {f["name"]: f["type"] for f in op["fields"]} for op in catalog
    }
    methods = "\n".join(method(op) for op in catalog if op["visibility"] != "lazy_only")
    text = (
        _HEADER.format(imports=_imports(methods))
        + "\n#: Ops whose wire form is typed (bare values and slots).\n"
        + f"TYPED_OPS: frozenset[str] = frozenset({names!r})\n\n"
        + "#: Each typed op's field types, as the catalogue describes them.\n"
        + f"OP_FIELDS: dict[str, dict[str, Any]] = {json.dumps(fields)}\n\n\n"
        + "class _OpsMixin:\n"
        + '    """The generated builder methods ``Pipeline`` inherits."""\n\n'
        + "    if TYPE_CHECKING:\n\n"
        + "        def _append_typed(self, op_name: str, values: dict[str, Any]) -> Pipeline: ...\n\n"
        + methods
    )
    # JSON's literals are Python's apart from these three.
    text = text.replace(": true", ": True").replace(": false", ": False")
    text = text.replace(": null", ": None")
    return ruff_format(text, filename="_ops_generated.py")


def generate() -> str:
    """Render from the committed catalogue."""
    return render(json.loads(CATALOG.read_text()))


def main() -> int:
    text = generate()
    if "--check" in sys.argv[1:]:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT.relative_to(_PKG)} is stale; run scripts/gen_ops.py")
            return 1
        return 0
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT.relative_to(_PKG)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
