#!/usr/bin/env python
"""Generate ``python/polars_cv/_dtype_names.py`` from ``dtype_table!``.

``dtype_table!`` (``view-buffer/src/core/dtype.rs``) is the single authority for
every spelling of a dtype: the short name, the VIEW wire code and the numpy
name. Rust reads it through three generated accessors, so the Rust side cannot
under-list. Python had no such path — it hand-typed the spellings it needed, and
one of those copies was wrong in a way that changes results:
``numpy_from_struct``'s allowlist admitted numpy *character codes*, so ``"u8"``
meant ``uint64`` and ``"i8"`` meant ``int64`` — the opposite of what those
strings mean everywhere else in this codebase, in a function exported from the
package root.

Generating closes that. The names are checked in rather than read over the FFI
because ``numpy_from_struct`` is pure Python and imports no ``_lib``: it must
keep working with no compiled extension. ``numpy_name`` does not cross the FFI
either — ``enum_variants`` carries variant names only — so there is nothing to
read at runtime without widening it.

Usage::

    python scripts/gen_dtype_names.py           # (re)write the module
    python scripts/gen_dtype_names.py --check   # exit 1 if it is stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# ``scripts/`` is not a package, and ``test_sanitation.py`` loads this module by
# path, which does not put the script's directory on ``sys.path`` the way
# running it as a script does. Sibling imports need it in both cases.
_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from _format import ruff_format  # noqa: E402

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DTYPE_RS = _REPO_ROOT / "view-buffer" / "src" / "core" / "dtype.rs"
_OUT_PATH = (
    Path(__file__).resolve().parents[1] / "python" / "polars_cv" / "_dtype_names.py"
)


def dtype_table_rows() -> list[tuple[str, str, int, str]]:
    """Parse ``dtype_table!``'s rows: ``(variant, short, wire_code, numpy)``.

    Read from source rather than the FFI because the wire codes are not
    surfaced across it — ``enum_variants`` carries names only. Source-scanning
    is the weaker technique, so it is used for exactly the part the FFI cannot
    answer, and the parse asserts it found a plausible table rather than
    silently matching nothing.

    Shared with ``tests/test_sanitation.py``, which needs the same rows for its
    wire-code and dtype-dispatch guards: a second parser of one table is the
    shape this whole file exists to remove.
    """
    src = _DTYPE_RS.read_text()
    assert "dtype_table!(" in src, "dtype_table! invocation not found — parse is broken"
    body = src.split("dtype_table!(", 1)[1]
    end = re.search(r"^\s*\);", body, re.M)
    assert end, "could not find the end of the dtype_table! invocation"
    body = body[: end.start()]
    rows = re.findall(
        r'\(\s*(\w+)\s*,\s*"([^"]+)"\s*,\s*(\d+)\s*,\s*"([^"]+)"\s*\)', body
    )
    # Cross-checked against an independent count of the invocation's rows, so a
    # mis-parse that swallows the rest of the file fails, while legitimately
    # adding an 11th dtype does not read as a parse bug.
    row_lines = [ln for ln in body.splitlines() if ln.strip().startswith("(")]
    assert len(rows) == len(row_lines), (
        f"dtype_table! parse found {len(rows)} rows but the invocation has "
        f"{len(row_lines)} lines starting a row — the scan is out of date"
    )
    assert rows, "dtype_table! parsed to zero rows"
    return [(v, s, int(c), n) for v, s, c, n in rows]


_HEADER = '''\
"""Dtype spellings, generated from ``dtype_table!``. Do not edit by hand.

``view-buffer/src/core/dtype.rs`` is the single authority for how a dtype is
spelled. This module is that table's Python face, regenerated by::

    python scripts/gen_dtype_names.py

``tests/test_sanitation.py::test_dtype_names_module_is_current`` fails if it is
stale, so the copy cannot drift from the table it came from.

Only the spellings live here. Which of them a given surface *accepts* is that
surface's own question — the numpy sink emits ``NUMPY_NAMES`` and nothing else,
so that is what ``numpy_from_struct`` admits.
"""

from __future__ import annotations

'''


def generate() -> str:
    """Render the module source."""
    rows = dtype_table_rows()
    short_names = [short for _, short, _, _ in rows]
    numpy_names = [numpy for _, _, _, numpy in rows]
    wire_codes = {short: code for _, short, code, _ in rows}

    lines = [_HEADER]
    lines.append(
        "#: Engine dtype names, as ``.cast()`` and ``source(dtype=)`` take them.\n"
    )
    lines.append(
        f"SHORT_NAMES: frozenset[str] = frozenset({sorted(short_names)!r})\n\n"
    )
    lines.append(
        "#: numpy dtype names, as the numpy/torch sink writes them into its struct.\n"
        "#:\n"
        "#: Deliberately not numpy's character codes. An earlier hand-written copy\n"
        '#: admitted those, which put ``"u8"`` (numpy ``uint64``) in the same set as\n'
        '#: this project\'s ``"u8"`` (``uint8``) — opposite meanings for one string.\n'
    )
    lines.append(
        f"NUMPY_NAMES: frozenset[str] = frozenset({sorted(numpy_names)!r})\n\n"
    )
    lines.append(
        "#: Every name the numpy/torch sink can write, which is one more than the\n"
        '#: engine has dtypes for: ``.sink("numpy", dtype="f16")`` downcasts float\n'
        "#: to half *at the encode boundary*, so ``float16`` reaches a consumer\n"
        "#: without ever being a `dtype_table!` row. Spelled as an explicit union\n"
        "#: rather than folded into the table: it is a property of the sink, not of\n"
        "#: the engine's dtype vocabulary.\n"
    )
    lines.append('SINK_NUMPY_NAMES: frozenset[str] = NUMPY_NAMES | {"float16"}\n\n')
    lines.append("#: Short name -> VIEW binary protocol code.\n")
    lines.append("WIRE_CODES: dict[str, int] = {\n")
    for short in short_names:
        lines.append(f"    {short!r}: {wire_codes[short]},\n")
    lines.append("}\n\n")
    lines.append(
        "#: VIEW binary protocol code -> numpy name. The reverse of\n"
        "#: :data:`WIRE_CODES` composed with the numpy spelling, emitted as one\n"
        "#: table because reading a VIEW blob needs exactly that hop and nothing\n"
        "#: else. `display.py` used to hand-write it, which made a third Python\n"
        "#: copy of `dtype_table!` guarded only by a regex over its own source.\n"
    )
    lines.append("NUMPY_BY_WIRE_CODE: dict[int, str] = {\n")
    for _, _, code, numpy in sorted(rows, key=lambda row: row[2]):
        lines.append(f"    {code}: {numpy!r},\n")
    lines.append("}\n\n")
    lines.append(
        "#: numpy name -> engine short name. The hop a caller needs to name the\n"
        "#: dtype of a column it is about to hand to ``source(dtype=)``: a Polars\n"
        "#: type spells itself the numpy way, the engine spells itself the short\n"
        "#: way. ``polars_cv.dtype_name_for`` is the public face of this table.\n"
        "#: It exists because metrics kept a hand-written copy of exactly this\n"
        "#: correspondence, guarded by a test that reached into a private to\n"
        "#: compare it against `dtype_table!`.\n"
    )
    lines.append("NUMPY_TO_SHORT: dict[str, str] = {\n")
    for _, short, _, numpy in sorted(rows, key=lambda row: row[3]):
        lines.append(f"    {numpy!r}: {short!r},\n")
    lines.append("}\n")
    return ruff_format("".join(lines), filename="_dtype_names.py")


def main() -> int:
    content = generate()
    if "--check" in sys.argv[1:]:
        current = _OUT_PATH.read_text() if _OUT_PATH.exists() else ""
        if current != content:
            print(
                f"{_OUT_PATH} is out of date. Run: python scripts/gen_dtype_names.py",
                file=sys.stderr,
            )
            return 1
        print(f"{_OUT_PATH.name} is up to date.")
        return 0
    _OUT_PATH.write_text(content)
    print(f"Wrote {_OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
