#!/usr/bin/env python
"""Generate ``python/polars_cv/_ops_generated.py`` from the typed op catalogue.

The catalogue (``tests/golden/op_catalog.json``) is emitted by the Rust op
definitions in ``src/ops/`` and pinned there by the Rust test
``catalog_matches_the_committed_file``; this script reads that file, never the
compiled extension, so it runs without a build. It writes:

- one ``str`` enum per registered Rust enum (``tests/golden/enum_catalog.json``,
  pinned by ``enum_catalog_matches_the_committed_file``), bar
  ``NOT_GENERATED``, docstring and spellings from the ``named_variants!``
  invocation;
- ``SourceFormat``/``SinkFormat``: the source and sink formats, from
  ``tests/golden/io_catalog.json`` (the
  Rust ``formats`` registry, pinned by ``io_catalog_matches_the_committed_file``);
- ``TYPED_OPS``: the op names that cross the wire in the typed form;
- ``OP_FIELDS``: each typed op's field types, which the builder's one encoder
  (``Pipeline._append_typed``) reads;
- ``_OpsMixin``: one builder method per op (``_``-prefixed for an internal op
  that hand-written sugar wraps), with the signature, defaults
  and docstring the Rust definition declares. ``Pipeline`` inherits it. A
  ``lazy_only`` op (one combining this expression with other graph nodes) has
  no ``Pipeline`` method: its builder is ``LazyPipelineExpr``'s, which owns the
  graph wiring, and ``test_every_lazy_only_op_is_a_lazy_method_with_its_fields``
  pins that method to the op's fields;
- ``_LazyOpsMixin``: that lazy method, for each ``lazy_only`` op whose one
  field is the other operand's node (the element-wise binary ops), all built by
  ``LazyPipelineExpr._binary_op``. ``LazyPipelineExpr`` inherits it; the
  multi-operand ``lazy_only`` ops stay hand-written there;
- ``_ContourOpsMixin``, ``_PointOpsMixin``, ``_BBoxOpsMixin``: every
  ``.contour``/``.point``/``.bbox`` accessor method, from
  ``tests/golden/geom_catalog.json`` (the Rust ``geom_fns`` definitions, pinned
  by ``geom_catalog_matches_the_committed_file``), each one call of the
  namespace's ``_call``.

Usage::

    python scripts/gen_ops.py            # (re)write the module
    python scripts/gen_ops.py --check    # exit 1 if it is stale
"""

from __future__ import annotations

import json
import re
import sys
import textwrap
from pathlib import Path
from typing import Any

_PKG = Path(__file__).resolve().parents[1]
CATALOG = _PKG / "tests" / "golden" / "op_catalog.json"
IO_CATALOG = _PKG / "tests" / "golden" / "io_catalog.json"
ENUM_CATALOG = _PKG / "tests" / "golden" / "enum_catalog.json"
PASS_CATALOG = _PKG / "tests" / "golden" / "pass_catalog.json"
GEOM_CATALOG = _PKG / "tests" / "golden" / "geom_catalog.json"

#: The geometry namespaces, in the order their mixins are written: the Rust
#: namespace key and the generated mixin's class name.
GEOM_NAMESPACES = (
    ("contour", "_ContourOpsMixin"),
    ("point", "_PointOpsMixin"),
    ("bbox", "_BBoxOpsMixin"),
)

#: Registered enums with no generated Python class, and why. Every other enum
#: in the catalogue becomes a ``str`` enum here, so a new registered enum gets
#: its Python class by being registered.
NOT_GENERATED = {
    # Python exposes the binary ops as LazyPipelineExpr methods, not an enum.
    "BinaryOp": "the binary ops are methods",
    # `.sink(dtype=)` passes the keyword through; the typed sink validates it.
    "SinkDType": "validated by the typed sink",
}
OUTPUT = _PKG / "python" / "polars_cv" / "_ops_generated.py"

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from _format import ruff_format  # noqa: E402

_HEADER = '''\
# This file is generated by scripts/gen_ops.py from tests/golden/op_catalog.json,
# io_catalog.json, enum_catalog.json, pass_catalog.json and geom_catalog.json. Do not edit by hand: change the Rust
# definition (src/ops/, src/formats/, src/geom_fns.rs), re-bless the catalogues
# (POLARS_CV_BLESS=1 cargo test -p polars-cv catalog_matches), then rerun the
# generator.
"""Builder methods generated from the typed op catalogue."""

from __future__ import annotations

{imports}
'''

#: Python annotation per catalogue scalar type, (per-row, literal).
_SCALAR = {
    "int": ("IntOrExpr", "int"),
    "float": ("FloatOrExpr", "float"),
    "bool": ("BoolOrExpr", "bool"),
}

#: Docstring width, less the method body's eight-space indent.
_DOC_WIDTH = 88 - 8

#: Docstring section headers the generated ``Args:`` block goes before.
_SECTION = re.compile(r"^(Example|Examples|Returns|Raises|Note|Notes|Warning):\s*$")


def annotation(ty: dict[str, Any]) -> str:
    """The Python annotation for a catalogue field type."""
    kind = ty["kind"]
    if kind == "scalar":
        if ty.get("variants"):
            return "str | pl.Expr" if ty["per_row"] else "str"
        per_row, literal = _SCALAR[ty["py"]]
        return per_row if ty["per_row"] else literal
    if kind == "optional":
        return f"{annotation(ty['inner'])} | None"
    if kind in ("array", "list"):
        return f"Sequence[{annotation(ty['inner'])}]"
    if kind == "one_of":
        return " | ".join(annotation(option) for option in ty["options"])
    if kind == "column":
        return "pl.Expr"
    if kind == "node":
        return "LazyPipelineExpr"
    msg = f"unknown catalogue type kind {kind!r}"
    raise ValueError(msg)


def _default(field: dict[str, Any]) -> str | None:
    if "default" in field:
        return repr(field["default"])
    if field["type"]["kind"] == "optional":
        return "None"
    return None


def _indent(text: str, prefix: str) -> str:
    return "\n".join(prefix + line if line.strip() else "" for line in text.split("\n"))


def docstring(op: dict[str, Any]) -> str:
    """The op doc with a Google ``Args:`` block from the field docs."""
    lines = op["doc"].split("\n")
    at = next((i for i, line in enumerate(lines) if _SECTION.match(line)), len(lines))
    args = []
    for field in op["fields"]:
        # Rewrapped: the Rust doc comment's line breaks sit at a different
        # indent, and the rendered line must fit the formatter's limit.
        args += textwrap.wrap(
            " ".join(field["doc"].split()),
            width=_DOC_WIDTH,
            initial_indent=f"    {field['name']}: ",
            subsequent_indent="        ",
        )
    block = ["Args:", *args] if args else []
    body = lines[:at]
    while body and not body[-1].strip():
        body.pop()
    tail = lines[at:]
    parts = [*body, "", *block]
    if tail:
        parts += ["", *tail]
    return "\n".join(parts).rstrip()


def method_name(op: dict[str, Any]) -> str:
    """The generated method's name.

    A ``public`` op is the Python method itself. An ``internal`` one is the
    building block a hand-written sugar method on ``Pipeline`` calls (``scale``
    adds ``out_dtype``/``preserve_dtype`` over ``_scale``), so it is private.
    """
    if op["visibility"] == "public":
        return op["python"]
    if op["visibility"] == "internal":
        return f"_{op['python']}"
    msg = f"gen_ops.py cannot yet place {op['visibility']} op {op['name']!r}"
    raise ValueError(msg)


def positional(op: dict[str, Any]) -> str | None:
    """The op's positional-or-keyword parameter, if it has one.

    The signature rule: an op with exactly one required field takes it
    positional-or-keyword (``.cast("f32")``, ``.threshold(128)``); every other
    parameter is keyword-only. Derived, never declared, so no op can opt out.
    """
    required = [
        f["name"]
        for f in op["fields"]
        if "default" not in f and f["type"]["kind"] != "optional"
    ]
    return required[0] if len(required) == 1 else None


def method(op: dict[str, Any]) -> str:
    """Render one builder method."""
    first = positional(op)
    fields = sorted(op["fields"], key=lambda f: f["name"] != first)
    params = ["self", *(["*"] if first is None and fields else [])]
    for field in fields:
        text = f"{field['name']}: {annotation(field['type'])}"
        default = _default(field)
        if default is not None:
            text += f" = {default}"
        params.append(text)
        if field["name"] == first and len(fields) > 1:
            params.append("*")
    values = ", ".join(f'"{f["name"]}": {f["name"]}' for f in op["fields"])
    doc = _indent(docstring(op), "        ").lstrip()
    return (
        f"    def {method_name(op)}({', '.join(params)}) -> Pipeline:\n"
        f'        """{doc}\n        """\n'
        f'        return self._append_typed("{op["name"]}", {{{values}}})\n'
    )


def geom_method(fn: dict[str, Any]) -> str:
    """Render one geometry accessor method.

    The accessors' signature rule: every required field is
    positional-or-keyword, in declaration order (``.translate(dx, dy)``,
    ``.iou(other)``); every field with a default, or optional, is keyword-only.
    """

    def required(f: dict[str, Any]) -> bool:
        return "default" not in f and f["type"]["kind"] != "optional"

    fields = [f for f in fn["fields"] if required(f)]
    rest = [f for f in fn["fields"] if not required(f)]
    params = ["self"]
    for field in fields:
        params.append(f"{field['name']}: {annotation(field['type'])}")
    if rest:
        params.append("*")
    for field in rest:
        params.append(
            f"{field['name']}: {annotation(field['type'])} = {_default(field)}"
        )
    values = ", ".join(f'"{f["name"]}": {f["name"]}' for f in fn["fields"])
    doc = _indent(docstring(fn), "        ").lstrip()
    return (
        f"    def {fn['python']}({', '.join(params)}) -> pl.Expr:\n"
        f'        """{doc}\n        """\n'
        f'        return self._call("{fn["name"]}", {{{values}}})\n'
    )


def geom_mixins(geom: list[dict[str, Any]]) -> str:
    """The geometry accessor mixins, one per namespace."""
    out = []
    for namespace, class_name in GEOM_NAMESPACES:
        methods = "\n".join(
            geom_method(fn) for fn in geom if fn["namespace"] == namespace
        )
        out.append(
            f"class {class_name}:\n"
            f'    """The generated ``.{namespace}`` accessor methods."""\n\n'
            "    if TYPE_CHECKING:\n\n"
            "        def _call(self, function: str, values: dict[str, Any]) -> pl.Expr: ...\n\n"
            + methods
        )
    return "\n\n".join(out)


def is_binary(op: dict[str, Any]) -> bool:
    """A ``lazy_only`` op whose only field is the other operand's node."""
    fields = op["fields"]
    return (
        op["visibility"] == "lazy_only"
        and len(fields) == 1
        and fields[0]["type"]["kind"] == "node"
    )


def lazy_method(op: dict[str, Any]) -> str:
    """Render one binary op's ``LazyPipelineExpr`` method."""
    (field,) = op["fields"]
    name = field["name"]
    doc = _indent(docstring(op), "        ").lstrip()
    return (
        f"    def {op['python']}(self, {name}: LazyPipelineExpr) -> LazyPipelineExpr:\n"
        f'        """{doc}\n        """\n'
        f'        return self._binary_op("{op["name"]}", {name})\n'
    )


def _imports(methods: str) -> str:
    """The import block: only what the rendered methods name (ruff F401)."""
    aliases = sorted(
        name
        for name in ("BoolOrExpr", "FloatOrExpr", "IntOrExpr")
        if re.search(rf"\b{name}\b", methods)
    )
    lines = []
    if "Sequence[" in methods:
        lines.append("from collections.abc import Sequence")
    lines.append("from dataclasses import dataclass")
    lines.append("from enum import Enum")
    lines.append("from typing import TYPE_CHECKING, Any\n\nif TYPE_CHECKING:")
    if "pl.Expr" in methods:
        lines.append("    import polars as pl\n")
    if aliases:
        lines.append(f"    from polars_cv._types import {', '.join(aliases)}")
    if "LazyPipelineExpr" in methods:
        lines.append("    from polars_cv.lazy import LazyPipelineExpr")
    lines.append("    from polars_cv.pipeline import Pipeline")
    return "\n".join(lines)


def format_enum(name: str, kind: str, formats: list[dict[str, Any]]) -> str:
    """A ``str`` enum of one pipeline end's formats, one member per format."""
    members = "".join(
        f'    {f["name"].upper()} = "{f["name"]}"\n'
        for f in sorted(formats, key=lambda f: f["name"])
    )
    return (
        f"class {name}(str, Enum):\n"
        f'    """Every {kind} format (typed per format in ``src/formats/``)."""\n\n'
        f"{members}"
    )


def named_enum(desc: dict[str, Any]) -> str:
    """A registered Rust enum as a ``str`` enum, one member per spelling."""
    members = "".join(
        f'    {v.upper().replace("-", "_")} = "{v}"\n' for v in desc["variants"]
    )
    doc = _indent(desc["doc"], "    ").lstrip()
    return f'class {desc["name"]}(str, Enum):\n    """{doc}\n    """\n\n{members}'


def opt_flag_fields(passes: list[dict[str, Any]]) -> str:
    """``OptFlags``' fields: one boolean per pass, on by default."""
    body = "".join(f"    {p['name']}: bool = True\n" for p in passes)
    return (
        "@dataclass(frozen=True)\n"
        "class _OptFlagFields:\n"
        '    """One boolean per optimisation pass, in catalogue order."""\n\n' + body
    )


def render(
    catalog: list[dict[str, Any]],
    io: dict[str, Any],
    enums: list[dict[str, Any]],
    passes: list[dict[str, Any]],
    geom: list[dict[str, Any]],
) -> str:
    """The whole generated module, formatted."""
    names = sorted(op["name"] for op in catalog)
    fields = {
        op["name"]: {f["name"]: f["type"] for f in op["fields"]} for op in catalog
    }
    methods = "\n".join(method(op) for op in catalog if op["visibility"] != "lazy_only")
    lazy_methods = "\n".join(lazy_method(op) for op in catalog if is_binary(op))
    geom_methods = geom_mixins(geom)
    text = (
        _HEADER.format(imports=_imports(methods + lazy_methods + geom_methods))
        + "\n\n"
        + "".join(
            named_enum(e) + "\n\n" for e in enums if e["name"] not in NOT_GENERATED
        )
        + format_enum("SourceFormat", "source", io["sources"])
        + "\n\n"
        + format_enum("SinkFormat", "sink", io["sinks"])
        + "\n\n#: Ops whose wire form is typed (bare values and slots).\n"
        + f"TYPED_OPS: frozenset[str] = frozenset({names!r})\n\n"
        + "#: Every optimisation pass, in the order they apply: (name, tier, summary).\n"
        + "PASS_CATALOG: tuple[tuple[str, str, str], ...] = "
        + repr(tuple((p["name"], p["tier"], p["summary"]) for p in passes))
        + "\n\n\n"
        + opt_flag_fields(passes)
        + "\n\n"
        + "#: Each typed op's field types, as the catalogue describes them.\n"
        + f"OP_FIELDS: dict[str, dict[str, Any]] = {json.dumps(fields)}\n\n\n"
        + "class _OpsMixin:\n"
        + '    """The generated builder methods ``Pipeline`` inherits."""\n\n'
        + "    if TYPE_CHECKING:\n\n"
        + "        def _append_typed(self, op_name: str, values: dict[str, Any]) -> Pipeline: ...\n\n"
        + methods
        + "\n\nclass _LazyOpsMixin:\n"
        + '    """The generated binary-op methods ``LazyPipelineExpr`` inherits."""\n\n'
        + "    if TYPE_CHECKING:\n\n"
        + "        def _binary_op(self, op: str, other: LazyPipelineExpr) -> LazyPipelineExpr: ...\n\n"
        + lazy_methods
        + "\n\n"
        + geom_methods
    )
    # JSON's literals are Python's apart from these three.
    text = text.replace(": true", ": True").replace(": false", ": False")
    text = text.replace(": null", ": None")
    return ruff_format(text, filename="_ops_generated.py")


def generate() -> str:
    """Render from the committed catalogue."""
    return render(
        json.loads(CATALOG.read_text()),
        json.loads(IO_CATALOG.read_text()),
        json.loads(ENUM_CATALOG.read_text()),
        json.loads(PASS_CATALOG.read_text()),
        json.loads(GEOM_CATALOG.read_text()),
    )


def main() -> int:
    text = generate()
    if "--check" in sys.argv[1:]:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT.relative_to(_PKG)} is stale; run scripts/gen_ops.py")
            return 1
        return 0
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT.relative_to(_PKG)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
