#!/usr/bin/env python
"""Generate ``python/polars_cv/lazy.pyi`` from the runtime ``LazyPipelineExpr``.

``LazyPipelineExpr``'s chainable operations are generated at import time from
``Pipeline`` (see :mod:`polars_cv.lazy`), so they have no hand-written source for
type checkers and IDEs to read. A ``.pyi`` stub shadows the ``.py`` for static
tooling; generating it straight from the fully-built class keeps it complete and
drift-free regardless of which methods are explicit and which are generated.

Usage::

    python scripts/gen_lazy_stub.py            # (re)write the stub
    python scripts/gen_lazy_stub.py --check     # exit 1 if the stub is stale
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path

# Make ``polars_cv`` importable when run from a source checkout.
_PKG_ROOT = Path(__file__).resolve().parent.parent / "python"
if str(_PKG_ROOT) not in sys.path:
    sys.path.insert(0, str(_PKG_ROOT))

# ``scripts/`` is not a package, and the diff test loads this module by path
# (``spec_from_file_location``), which does not put the script's directory on
# ``sys.path`` the way running it as a script does. Sibling imports need it in
# both cases.
_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from _format import ruff_format  # noqa: E402

from polars_cv.lazy import LazyPipelineExpr  # noqa: E402

_STUB_PATH = _PKG_ROOT / "polars_cv" / "lazy.pyi"

_HEADER = """\
# This file is auto-generated by scripts/gen_lazy_stub.py. Do not edit by hand.
#
# LazyPipelineExpr's chainable operations are generated from Pipeline at import
# time (see lazy.py); this stub mirrors that surface so type checkers and IDEs
# can resolve the methods. Regenerate after changing Pipeline:
#
#     python scripts/gen_lazy_stub.py

from collections.abc import Sequence
from typing import Any

import polars as pl

from polars_cv._graph import PipelineGraph
from polars_cv._types import ({types_import})
from polars_cv.pipeline import Pipeline

PIPELINE_ONLY_METHODS: frozenset[str]

def _chainable_pipeline_ops() -> list[str]: ...
def _generate_node_id() -> str: ...
"""


def _types_referenced(body: str) -> list[str]:
    """Every `polars_cv._types` name the rendered stub actually mentions.

    Derived, not hand-listed. The import block used to be a literal, so adding
    a `Pipeline` parameter annotated with any type it did not happen to name
    produced a stub referencing an undefined symbol -- and
    `test_lazy_stub_is_current` could not catch it, being a
    regenerate-and-diff with the same defect on both sides. `scale_contour`'s
    `origin: ScaleOrigin | str | pl.Expr` is the case that proved it.
    """
    import ast

    import polars_cv._types as types_module

    # Names `_types` *defines*, read from its source -- not `dir()`, which also
    # answers with everything it imports (`pl`, `Any`, ...) and would emit an
    # import block that re-exports them from the wrong module.
    tree = ast.parse(Path(types_module.__file__).read_text())
    defined: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            defined.add(node.name)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            defined.add(node.target.id)
        elif isinstance(node, ast.Assign):
            defined.update(
                t.id for t in node.targets if isinstance(t, ast.Name)
            )

    referenced = sorted(
        name
        for name in defined
        if not name.startswith("_") and re.search(rf"\b{re.escape(name)}\b", body)
    )
    assert referenced, (
        "no polars_cv._types names found in the rendered stub -- the scan is "
        "broken and would emit an empty import block"
    )
    return referenced


def _render_annotation(annotation: object) -> str:
    """Render a parameter/return annotation. Annotations are strings here because
    the source modules use ``from __future__ import annotations``."""
    if annotation is inspect.Parameter.empty:
        return ""
    if isinstance(annotation, str):
        return annotation
    return getattr(annotation, "__name__", str(annotation))


def _render_param(param: inspect.Parameter) -> str:
    if param.kind is inspect.Parameter.VAR_POSITIONAL:
        prefix = "*"
    elif param.kind is inspect.Parameter.VAR_KEYWORD:
        prefix = "**"
    else:
        prefix = ""
    text = f"{prefix}{param.name}"
    ann = _render_annotation(param.annotation)
    if ann:
        text += f": {ann}"
    # Stub convention: elide concrete default values with ``...``.
    if param.default is not inspect.Parameter.empty:
        text += " = ..." if ann else "=..."
    return text


def _render_signature(sig: inspect.Signature) -> str:
    parts: list[str] = []
    saw_var_positional = False
    for param in sig.parameters.values():
        if param.kind is inspect.Parameter.KEYWORD_ONLY and not saw_var_positional:
            parts.append("*")
            saw_var_positional = True
        if param.kind is inspect.Parameter.VAR_POSITIONAL:
            saw_var_positional = True
        parts.append(_render_param(param))
    ret = _render_annotation(sig.return_annotation)
    ret_text = f" -> {ret}" if ret else ""
    return f"({', '.join(parts)}){ret_text}"


def _render_member(name: str, member: object) -> str | None:
    """Render a single class member (method or property) as a stub line."""
    if isinstance(member, property):
        sig = inspect.signature(member.fget)  # type: ignore[arg-type]
        return f"    @property\n    def {name}{_render_signature(sig)}: ...\n"
    if inspect.isfunction(member):
        sig = inspect.signature(member)
        return f"    def {name}{_render_signature(sig)}: ...\n"
    return None


def generate_stub() -> str:
    body: list[str] = []
    for name, member in vars(LazyPipelineExpr).items():
        if name.startswith("__") and name not in ("__init__", "__repr__", "__str__"):
            continue
        rendered = _render_member(name, member)
        if rendered is not None:
            body.append(rendered)
    rendered_body = "\n".join(body)

    # The import block is derived from what the body references, so a new
    # annotation cannot leave the stub naming an undefined symbol.
    header = _HEADER.format(
        types_import="\n    " + ",\n    ".join(_types_referenced(rendered_body)) + ",\n"
    )
    return ruff_format(
        "".join([header, "\nclass LazyPipelineExpr:\n", rendered_body]),
        filename="lazy.pyi",
    )


def main() -> int:
    content = generate_stub()
    if "--check" in sys.argv[1:]:
        current = _STUB_PATH.read_text() if _STUB_PATH.exists() else ""
        if current != content:
            print(
                f"{_STUB_PATH} is out of date. Run: python scripts/gen_lazy_stub.py",
                file=sys.stderr,
            )
            return 1
        print(f"{_STUB_PATH.name} is up to date.")
        return 0
    _STUB_PATH.write_text(content)
    print(f"Wrote {_STUB_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
