#!/usr/bin/env python
"""Generate ``python/polars_cv/lazy.pyi`` from the runtime ``LazyPipelineExpr``.

``LazyPipelineExpr``'s chainable operations are generated at import time from
``Pipeline`` (see :mod:`polars_cv.lazy`), so they have no hand-written source for
type checkers and IDEs to read. A ``.pyi`` stub shadows the ``.py`` for static
tooling; generating it straight from the fully-built class keeps it complete and
drift-free regardless of which methods are explicit and which are generated.

Usage::

    python scripts/gen_lazy_stub.py            # (re)write the stub
    python scripts/gen_lazy_stub.py --check     # exit 1 if the stub is stale
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path

# Make ``polars_cv`` importable when run from a source checkout.
_PKG_ROOT = Path(__file__).resolve().parent.parent / "python"
if str(_PKG_ROOT) not in sys.path:
    sys.path.insert(0, str(_PKG_ROOT))

from polars_cv.lazy import LazyPipelineExpr  # noqa: E402

_STUB_PATH = _PKG_ROOT / "polars_cv" / "lazy.pyi"

_HEADER = """\
# This file is auto-generated by scripts/gen_lazy_stub.py. Do not edit by hand.
#
# LazyPipelineExpr's chainable operations are generated from Pipeline at import
# time (see lazy.py); this stub mirrors that surface so type checkers and IDEs
# can resolve the methods. Regenerate after changing Pipeline:
#
#     python scripts/gen_lazy_stub.py

from typing import Any

import polars as pl

from polars_cv._graph import PipelineGraph
from polars_cv._types import FloatOrExpr, HashAlgorithm, IntOrExpr
from polars_cv.pipeline import Pipeline

PIPELINE_ONLY_METHODS: frozenset[str]

def _chainable_pipeline_ops() -> list[str]: ...
def _generate_node_id() -> str: ...
"""


def _render_annotation(annotation: object) -> str:
    """Render a parameter/return annotation. Annotations are strings here because
    the source modules use ``from __future__ import annotations``."""
    if annotation is inspect.Parameter.empty:
        return ""
    if isinstance(annotation, str):
        return annotation
    return getattr(annotation, "__name__", str(annotation))


def _render_param(param: inspect.Parameter) -> str:
    if param.kind is inspect.Parameter.VAR_POSITIONAL:
        prefix = "*"
    elif param.kind is inspect.Parameter.VAR_KEYWORD:
        prefix = "**"
    else:
        prefix = ""
    text = f"{prefix}{param.name}"
    ann = _render_annotation(param.annotation)
    if ann:
        text += f": {ann}"
    # Stub convention: elide concrete default values with ``...``.
    if param.default is not inspect.Parameter.empty:
        text += " = ..." if ann else "=..."
    return text


def _render_signature(sig: inspect.Signature) -> str:
    parts: list[str] = []
    saw_var_positional = False
    for param in sig.parameters.values():
        if param.kind is inspect.Parameter.KEYWORD_ONLY and not saw_var_positional:
            parts.append("*")
            saw_var_positional = True
        if param.kind is inspect.Parameter.VAR_POSITIONAL:
            saw_var_positional = True
        parts.append(_render_param(param))
    ret = _render_annotation(sig.return_annotation)
    ret_text = f" -> {ret}" if ret else ""
    return f"({', '.join(parts)}){ret_text}"


def _render_member(name: str, member: object) -> str | None:
    """Render a single class member (method or property) as a stub line."""
    if isinstance(member, property):
        sig = inspect.signature(member.fget)  # type: ignore[arg-type]
        return f"    @property\n    def {name}{_render_signature(sig)}: ...\n"
    if inspect.isfunction(member):
        sig = inspect.signature(member)
        return f"    def {name}{_render_signature(sig)}: ...\n"
    return None


def _ruff_format(text: str) -> str:
    """Normalise the stub through ``ruff format`` so it matches CI's check.

    Falls back to the raw text if ruff is unavailable (it is a dev dependency,
    so this only matters outside the configured dev environment)."""
    import shutil
    import subprocess

    ruff = shutil.which("ruff") or str(Path(sys.executable).parent / "ruff")
    try:
        proc = subprocess.run(
            [ruff, "format", "--stdin-filename", "lazy.pyi", "-"],
            input=text,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return text
    return proc.stdout


def generate_stub() -> str:
    lines = [_HEADER, "\nclass LazyPipelineExpr:\n"]
    body: list[str] = []
    for name, member in vars(LazyPipelineExpr).items():
        if name.startswith("__") and name not in ("__init__", "__repr__", "__str__"):
            continue
        rendered = _render_member(name, member)
        if rendered is not None:
            body.append(rendered)
    lines.append("\n".join(body))
    return _ruff_format("".join(lines))


def main() -> int:
    content = generate_stub()
    if "--check" in sys.argv[1:]:
        current = _STUB_PATH.read_text() if _STUB_PATH.exists() else ""
        if current != content:
            print(
                f"{_STUB_PATH} is out of date. Run: python scripts/gen_lazy_stub.py",
                file=sys.stderr,
            )
            return 1
        print(f"{_STUB_PATH.name} is up to date.")
        return 0
    _STUB_PATH.write_text(content)
    print(f"Wrote {_STUB_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
